### ISSUE TITLE
PHPUnit Tests: Could not register permissions

### ISSUE THREAD

**Issue by shiroamada** [Laravel-Backpack/PermissionManager#107]
testing.ALERT: Could not register permissions because SQLSTATE[42S02]: Base table or view not found: 1146 Table 'project_testing.permissions' doesn't exist (SQL: select * from `permissions`)

Is it not working with TestCase? Tested with sqlite memory and mysql real db.

Laravel: 5.4.30
"backpack/permissionmanager": "^2.1"

I want to mock a writer role.
```
 $user = new User(
            ['roles' =>
                 [
                     [
                         'id' => '2',
                         'name' => 'Writer',
                         "created_at" => "2017-07-21 20:53:25",
                         "updated_at" => "2017-07-21 20:53:25",
                         "pivot" => [
                            "user_id" => 1,
                            "role_id" => 1
                         ],
                     ]
                 ],
            ]
        );

        $this->be($user); //set user as writer
```

**Comment by lloy0076** [comment]
Does the permissions table exist? If it doesn't then that's the obvious error...
