### ISSUE TITLE
Missing value errors

### ISSUE THREAD

**Issue by microdesign** [Laravel-Backpack/PermissionManager#113]
ErrorException
Undefined variable: errors (View: /Volumes/Storage/Projects/lexicon/vendor/backpack/crud/src/resources/views/form_content.blade.php) (View: /Volumes/Storage/Projects/lexicon/vendor/backpack/crud/src/resources/views/form_content.blade.php)

I don't extend anything - only the routes

**Comment by lloy0076** [comment]
Did you install the package as per the docs? https://laravel-backpack.readme.io/docs/features

**Comment by microdesign** [comment]
Of course

**Comment by microdesign** [comment]
The same error is in your page manager -> create/edit pages

<img width="1139" alt="screen shot 2017-09-01 at 7 59 04 pm" src="https://user-images.githubusercontent.com/3175952/29979916-0f4c5c16-8f50-11e7-8dc0-9b3420569083.png">

**Comment by tabacitu** [comment]
Hi @microdesign . Thanks for metioning it. The error has since been fixed, so a ```composer update``` should fix it for you, sorry for not letting you know here at the time.

Cheers!
