### ISSUE TITLE
Replace laravel backpack error message with custom message.

### ISSUE THREAD

**Issue by inquisitive-stha** [Laravel-Backpack/PermissionManager#117]
I have a requirement to delete an entry from employer table but it cannot be deleted as it needs to delete all the entry from job tables related to this employer. So, instead of just showing error "not deleted". I want to pop up a message such as  Before, deleting employer you need to delete the job first related to this employer."

I want to replace the message of the following image.
![msg](https://user-images.githubusercontent.com/16288854/30001285-07bdadc4-90a9-11e7-9f36-0db0d6167bda.png)

**Comment by lloy0076** [comment]
@inquisitive-stha - in the CrudController somewhere in `app/Http/Controllers/Admin` (assuming you haven't moved it somewhere else) you'd need to override the `destroy` method [unless it's called `delete` but I'm fairly certain you want `destroy`].

Check the underlying implementation from the base class.

**Comment by inquisitive-stha** [comment]
I didn't understand clearly. Could you please, explain it in deep.
If I were not using backpack, I could use something like

```
if(count($job)>0)
{
  return redirect('admin/employer')->with('message','Before deleting employer you need to delete the job created by this user at first');
}
```

In view,

```
     @if(session()->has('message'))
            <div class="alert alert-danger disappear" >
                <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
                <strong>{{ session()->get('message') }}</strong>
            </div>
      @endif
```

How can I achieve similar like this, in the backpack? I just want to replace message shown in above picture with a custom message if the requirement meets.

**Comment by lloy0076** [comment]
Actually it's not quite as easy as it looks, there's a few places you'll need to fiddle about in:

1. You'll need to adjust the CrudController's `destroy()` method to return some sentinel value that's not `true`
2. Then you'll need to publish the Crud vendor resources; then in `resources/views/vendor/backpack/crud/list.blade.php` and find https://github.com/Laravel-Backpack/CRUD/blob/a1e67c526311640437bdc4f840a8c9288eddc1ec/src/resources/views/list.blade.php#L279
3. Figure out what you want to do there (I'll leave that as an exercise for you).

**Comment by Spodnet** [comment]
I've just implemented the following changes to make something similar happen, I want to show a message on delete that says something more useful

In my controller I've overridden the destroy method and returns

```php
if ($office->contacts->count() > 0) {
    return (new \Illuminate\Http\Response)->setStatusCode(403, trans('errors.contacts exist'));
} else {
    return (string) $office->delete();
}
```

This returns a 403 with the status set as the error message

In the list view I've changed the error handling to

```javascript
// Show an alert with the result
var text = "{{ trans('backpack::crud.delete_confirmation_not_message') }}";

if (result.status == 403) {
    text = result.statusText;
}

new PNotify({
    title: "{{ trans('backpack::crud.delete_confirmation_not_title') }}",
    text: text,
    type: "warning"
});
```
