### ISSUE TITLE
L5.5 missing package auto discovery

### ISSUE THREAD

**Issue by cristianuibar** [Laravel-Backpack/PermissionManager#119]
I have noticed this when my routes were not getting registered and got 404.

**Comment by lloy0076** [comment]
@tabacitu - this does seem to be the case.

**Comment by lloy0076** [comment]
I'm not convinced that a lack of auto-discovery is a bug - it's really an enhancement I suppose.

Nonetheless, the PR is ready anyway.

**Comment by cristianuibar** [comment]
Yet you are not consistent if all of backpack packages are auto discoverable enabled and this one isn't.

**Comment by cristianuibar** [comment]
Maybe a warning in the Readme if you wish to keep this behavior.

**Comment by lloy0076** [comment]
I agree that it's inconsistent and it _might_ be arguable that inconsistency is a bug; it'll be just as easy to make the package auto-discoverable as it will be to adjust the README (which will need to be adjusted anyway).

In fact, https://github.com/Laravel-Backpack/PermissionManager/pull/121 is waiting to be merged!

**Comment by tabacitu** [comment]
Done, thanks guys!
