### ISSUE TITLE
Can't use @hasanyroles on blade directives

### ISSUE THREAD

**Issue by Freizello** [Laravel-Backpack/PermissionManager#123]
why i can't  use @hasanyrole like [spatie/laravel-permission](https://github.com/spatie/laravel-permission)?
```
@hasanyrole($collectionOfRoles)
    I have one or more of these roles!
@else
    I have none of these roles...
@endhasanyrole
// or
@hasanyrole('writer|admin')
    I am either a writer or an admin or both!
@else
    I have none of these roles...
@endhasanyrole
```

**Comment by lloy0076** [comment]
I don't know - can you elaborate on why you think you cannot?

i.e. what is your setup and what is not working, are there any logs showing an issue?

**Comment by pulkitarunsharma** [comment]
@hasanyrole('writer|admin')
    I am either a writer or an admin or both!
@else
    I have none of these roles...
@endhasanyrole


In this roles after | didnt work. As here I will pass only for writer not for admin.  i am also dealing with same issue

**Comment by lloy0076** [comment]
@pulkitarunsharma - do:

```
@hasanyrole(['write', 'admin'])
```

That calls up to this [line](https://github.com/spatie/laravel-permission/blob/v1/src/Traits/HasRoles.php#L158) which then calls `hasRole` reproduced [here](https://github.com/spatie/laravel-permission/blob/v1/src/Traits/HasRoles.php#L128):

```
    public function hasRole($roles)
    {
        if (is_string($roles)) {
            return $this->roles->contains('name', $roles);
        }
        if ($roles instanceof Role) {
            return $this->roles->contains('id', $roles->id);
        }
        if (is_array($roles)) {
            foreach ($roles as $role) {
                if ($this->hasRole($role)) {
                    return true;
                }
            }
            return false;
        }
        return (bool) $roles->intersect($this->roles)->count();
    }
```

Your second one just shouldn't work.

I would note that your issue doesn't seem to be with Backpack itself and I'd encourage you, maybe, to investigate the upstream package [here](https://github.com/spatie/laravel-permission/tree/v1) for further information.
