### ISSUE TITLE
Base table or view not found role_users doesn't exist

### ISSUE THREAD

**Issue by cvassios-ekko** [Laravel-Backpack/PermissionManager#124]
I was working through the installation instructions and after I added the links to the menu, when I visit the Users pages, I get an error:

"Base table or view not found: 1146 Table 'example.role_users' doesn't exist"

Looking at the migrations file I don't find reference to the role_users table.

Using Laravel 5.4.18

**Comment by lloy0076** [comment]
Usually this means that the migrations haven't been run:

```
$ php artisan vendor:publish --provider="Backpack\PermissionManager\PermissionManagerServiceProvider" #publish config files and migration
$ php artisan migrate #create the role and permission tables
```

However, I've followed the instructions on L5.5 and I can't see that they're running unless I'm doing something wrong (which I claim I'm not).

I'll look into this as a potential bug.

**Comment by tabacitu** [comment]
Guys, just tried it and installation worked fine for me - must have been not following the docs properly, so I'll close this. Please reopen if I'm wrong. Cheers!
