### ISSUE TITLE
Already have  "spatie/laravel-permission": "^2.7",

### ISSUE THREAD

**Issue by packytagliaferro** [Laravel-Backpack/PermissionManager#125]
So I have  `"spatie/laravel-permission": "^2.7" `that I am using in my project already. I came across Backpacks Roles Manager and tried to install it. I get an error since the package needs  `"spatie/laravel-permission": "^1.4"`. Since I am already using the Roles is there a way to just get the Manager part and not install `spatie` again or the migrations??

**Comment by lloy0076** [comment]
You could try merging in the PR from here:

* https://github.com/Laravel-Backpack/PermissionManager/pull/118

**Comment by tabacitu** [comment]
We're currently working on support for 2.7 - but there are MAJOR changes. We need to develop upgrade guides and make sure everybody's apps remain functional. The guys at Spatie push breaking changes all the time. Very difficult to provide support for their latest version.
