### ISSUE TITLE
/admin/user/search? Endpoint throws AccessDeniedException

### ISSUE THREAD

**Issue by andrevv11** [Laravel-Backpack/PermissionManager#128]
I am getting a https://datatables.net/manual/tech-notes/7 warning. This is because 

```
Backpack \ CRUD \ Exception \ AccessDeniedException
Unauthorized access - you do not have the necessary permissions to see this page.
```
Is being thrown at the user/search? endpoint. 

I have no permissions setup that should affect the access of these panels?

Thanks

**Comment by andrevv11** [comment]
Composer packages installed:
```
"require": {
        "php": ">=7.0.0",
        "algolia/algoliasearch-client-php": "^1.22",
        "backpack/base": "^0.7.25",
        "backpack/crud": "^3.2",
        "backpack/logmanager": "^2.3",
        "backpack/pagemanager": "^1.1",
        "backpack/permissionmanager": "^2.1",
        "backpack/settings": "^2.0",
        "christiankuri/laravel-favorite": "^1.2",
        "fideloper/proxy": "~3.3",
        "laravel/framework": "^5.5",
        "laravel/scout": "^3.0",
        "laravel/socialite": "^3.0",
        "laravel/tinker": "~1.0",
        "pda/pheanstalk": "^3.1"
    }```

**Comment by gabriel-cardoso** [comment]
Are you sure your `user_model` is correctly set in `permissionmanager.php` file ?
Mine is: `'user_model' => 'App\Models\AdminUser'`

**Comment by tabacitu** [comment]
@andrevv11 apparently we've accidentally pushed a version of PermissionManager that requires CRUD 3.3 without that being explicit in the composer.json - please [upgrade your CRUD to 3.3](https://laravel-backpack.readme.io/docs/upgrading-crud-32-to-33).

Cheers!
