### ISSUE TITLE
Question: Class Role not found

### ISSUE THREAD

**Issue by wink-** [Laravel-Backpack/PermissionManager#13]
_@role('writer')_ works
_@hasrole('writer')_ works
_@can('special.permission')_ works

_@hasanyrole(Role::all())_ however kicks an error Class Role not found. 

My config file references  _'role' => Backpack\PermissionManager\app\Models\Role::class,_
and the Role.php file containing the class is there at that address. I am guessing it is either not autoloading or something.

Any tips?

**Comment by tabacitu** [comment]
Hi @wink-, 

You probably need to ```namespace Backpack\PermissionManager\app\Models\Role as Role;``` in your controller.

Or if you want it available globally, you can add aliases in your config/app.php file:
```php
        'Role' => Backpack\PermissionManager\app\Models\Role::class,
        'Permission' => Backpack\PermissionManager\app\Models\Permission::class,
```

**Comment by wink-** [comment]
Both worked perfectly! Thank you!
