### ISSUE TITLE
Permission Manager doesnt work

### ISSUE THREAD

**Issue by rasez** [Laravel-Backpack/PermissionManager#130]
I install PermissionManager and create a role I set permission edit and view to this role and set role to users but in list page show delete button again

**Comment by lloy0076** [comment]
The permission manager simply sets up permissions - it doesn't actually enforce them.

Thus, one can make a permission called `DENY-ALL` but nothing will be denied to anyone unless one actually checks for the presence of that permission and does something [or in this case, probably does not do something].
