### ISSUE TITLE
Blocked a route with a middleware

### ISSUE THREAD

**Issue by Jimmylet** [Laravel-Backpack/PermissionManager#131]
Hello,

I'm trying to use a middleware to disallow access to a CRUD route.

Only, this package does not seem to allow it. With Spatie / laravel-permissions, we can do it by creating a middleware. However, you need v 2.x, PermissionsManager only uses 1.x and I can not update.

Do you have a solution to block a road with this version?

When will a next update arrive? This package is very useful.

Thank you very much !

**Comment by lloy0076** [comment]
Creating a middleware for the elder version of Laravel Spatie isn't difficult and is discussed:

* https://github.com/spatie/laravel-permission/tree/v1#using-a-middleware

#118 discusses upgrading to a 2.X version.

Feel free to re-open if you need further help.

**Comment by Jimmylet** [comment]
Yes, it works. Thank you!
