### ISSUE TITLE
Allowing/disallowing access to crud resources based off user permissions?

### ISSUE THREAD

**Issue by OwenMelbz** [Laravel-Backpack/PermissionManager#14]
I've just started to look at backpack, and have never used any laravel authentication before, so I'm struggling a little here with users.

I've created a new crud controller which works fine, however I'm wanting to limit access to it to users who have the permission `teams.update`

I've been digging around the documentation and still cant figure it out, I'm not sure if i'm doing this completely wrong or what.

My 3 theories were

`$this->crud->allowAccess('teams.update')` I was hoping this would only allow access to people who have `teams.update` but that didnt work.

My second theory was - but this always returned false

```php
if( !$this->crud->hasAccess('teams.update') ) {
    $this->crud->denyAccess('teams.update');
}

```

My final theory was - but `$user` was always `null`, maybe because im in the controller construct?

```php

$user = Auth::user();

if( !$user->hasPermissionTo('teams.update') ) {
    $this->crud->denyAccess('teams.update');
}

```

Help. Please :(

**Comment by tabacitu** [comment]
Hi @owenmelbz,

You're onto it! :-)
The third option is the winner. It used to work just like that in Laravel 5.2, but since Laravel 5.3 the auth is bo longer available in the constructor. That leaves you (us) with 2 options:
1) use a [closure-based middleware](https://laravel-news.com/2016/08/controller-construct-session-changes-in-laravel-5-3/)
2) do it in your EntityCrudController::edit() method (that overwrites the CrudController::edit() method), and after that just call parent::edit() so no other functionality is changed;

Sorry for no the lack of code, on mobile.
Tell me if this works for you.

Cheers!

**Comment by OwenMelbz** [comment]
Ah okay, that would explain things :)

As all our crud entities will need to be checked for authentication the same way, Im thinking the middleware method might not be the best, without copy/pasting the code into every controller.

Would you think a better approach would to be something as below

1. Creating an Application level controller `app/Http/Controllers/Admin/ApplicationCrudController.php`

```php

class ApplicationCrudController extends CrudController {

    protected $user = null;
    
    public function index()
    {
        $this->user = Auth::user();
        return parent::index();
    }

}

```

then changing all my other controllers to extend that instead? like

```php
class TeamCrudController extends ApplicationCrudController {

}
```

(Im new to this stuff so not sure the best way to do it in systems like laravel)

Thanks

**Comment by OwenMelbz** [comment]
For anybody else - this is my current solution, albeit not perfect or finished, but I'm just playing/learning currently

**File:**  `app/Http/Controllers/Admin/AppCrudController.php`
```php
<?php namespace App\Http\Controllers\Admin;

use Backpack\CRUD\app\Http\Controllers\CrudController;

use App\Http\Traits\ApplicationPermissions;

class AppCrudController extends CrudController {

    use ApplicationPermissions;

    public function index()
    {
        $this->setRequiredPermissions(['list', 'create', 'update', 'delete']);
        return parent::index();
    }

    public function create()
    {
        $this->setRequiredPermissions(['list', 'create']);
        return parent::create();
    }

    public function edit($id)
    {
        $this->setRequiredPermissions(['list', 'update']);
        return parent::edit($id);
    }

    public function destroy($id)
    {
        $this->setRequiredPermissions(['list', 'update', 'delete']);
        return parent::destroy($id);
    }

    public function reorder()
    {
        $this->setRequiredPermissions(['list', 'update']);
        return parent::reorder();
    }
}
```


**File:**  `app/Http/Controllers/Admin/ShaunCrudController.php`
```php
<?php namespace App\Http\Controllers\Admin;

use Backpack\CRUD\app\Http\Controllers\CrudController;

use App\Http\Requests\ShaunRequest as StoreRequest;
use App\Http\Requests\ShaunRequest as UpdateRequest;

class ShaunCrudController extends AppCrudController {

	public function __construct()
   {
        parent::__construct();

        $this->crud->setModel("App\Models\Shaun");
        $this->crud->setRoute("admin/shaun");
        $this->crud->setEntityNameStrings('Shaun', 'Shauns\'');
		$this->crud->setFromDb();
    }

    public function store(StoreRequest $request)
	{
		return parent::storeCrud();
	}

	public function update(UpdateRequest $request)
	{
		return parent::updateCrud();
	}
}

```

**File**: `app/Http/Traits/ApplicationPermissions.php`
```php
<?php namespace App\Http\Traits;

use Auth;

trait ApplicationPermissions {

    protected $user = null;

    public function setRequiredPermissions( $permissions = [] )
    {
        if( !$this->user ){
            $this->user = Auth::user();
        }

        foreach($permissions as $permission){

            $permissionName = $this->crud->route . '/' . $permission;

            //Test if the user has the above permission
            if( $this->user->hasPermissionTo($permissionName) ){
                $this->crud->allowAccess($permission);
            }
            else {
                $this->crud->denyAccess($permission);
            }
        }
    }
}
```

**Comment by Darival** [comment]
i created a middleware
```php
<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Support\Facades\Auth;

class hasRoles
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     *
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        if (!Auth::check()) {
            return redirect('admin/login');
        }
        // Get the required roles from the route
        $roles = $this->getRequiredRoleForRoute($request->route());
        // Check if a role is required for the route, and
        // if so, ensure that the user has that role.
        if ($request->user()->hasRole($roles) || !$roles) {
            return $next($request);
        }

        if ($request->ajax() || $request->wantsJson()) {
            return response(trans('backpack::base.unauthorized'), 401);
        } else {
            return redirect('/');
        }
    }

    private function getRequiredRoleForRoute($route)
    {
        $actions = $route->getAction();

        return isset($actions['roles']) ? $actions['roles'] : null;
    }
}
```
and on my route

```php
Route::group(['prefix'=>'admin','middleware' => ['hasRoles'], 'roles' => 'Admin'], function () {
    CRUD::resource('category', 'Admin\ProductCategoryCrudController');
    CRUD::resource('product', 'Admin\ProductCrudController');
    CRUD::resource('permission', 'Admin\PermissionCrudController');
    CRUD::resource('role', 'Admin\RoleCrudController');
    CRUD::resource('user', 'Admin\UserCrudController');
    Route::get('dashboard', 'Admin\DashboardController@dashboard');
    Route::get('/', 'Admin\DashboardController@dashboard');
});
```

**Comment by OwenMelbz** [comment]
@Darival Thanks for your suggestion, I'm wondering if purely basing it on roles sort of invalidates the point of permissions? As how would you allow Read-Only users on Controller X?

**Comment by Darival** [comment]
@OwenMelbz You are right, that approach is not the best for every scenario, but you can also create a middleware to check permissions the same way.

```php
<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Support\Facades\Auth;

class hasPermissions
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     *
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        if (!Auth::check()) {
            return redirect('admin/login');
        }
        // Get the required roles from the route
        $permissions = $this->getRequiredPermissionsForRoute($request->route());
        // Check if a role is required for the route, and
        // if so, ensure that the user has that role.
        if ($request->user()-> hasPermissionTo($permissions) || !$permissions) {
            return $next($request);
        }

        if ($request->ajax() || $request->wantsJson()) {
            return response(trans('backpack::base.unauthorized'), 401);
        } else {
            return redirect('/admin');
        }
    }

    private function getRequiredPermissionsForRoute($route)
    {
        $actions = $route->getAction();

        return isset($actions['permissions']) ? $actions['permissions'] : null;
    }
}
```
I only had to change the word "role" => "permission" from the other middleware and the method "hasRole" => "hasPermissionTo" , huehue

**Comment by tabacitu** [comment]
Very, _very_ nice collaboration work here! I think the middleware solution is so clean and sexy! And I love the permission generator. Very nice solution, @OwenMelbz , and very nice addition, @Darival . Threads like this bring a big smile to my face :-) 

I personally prefer to check for permissions, not roles, but I admit for some applications roles are enough. So I think both ```hasRoles``` and ```hasPermissions``` are important.

Here's what I think the optimal solution would be. And if you agree with me, I think we should include it in Backpack\PermissionManager, to save us some hassle the next time:

1) We use the ```permissionGenerator``` @OwenMelbz suggested to generate all needed permissions.
2) We use the ```hasRoles``` and ```hasPermissions``` middleware @Darival suggested to check for permission. 
3) We encourage people in the docs to use those middleware either in the routes file, or [directly in their Controllers](https://laravel.com/docs/5.3/controllers#controller-middleware). 

Questions:
(A) @OwenMelbz , @Darival , @mariusconstantin2503 , what do you think? best of both worlds? nice to include in the package?
(B) I'm not quite sure if we should use the ```hasPermissions``` and ```hasRoles``` syntax for the middleware or use t[he one suggested by spatie/permissionmanager](https://github.com/spatie/laravel-permission#using-a-middleware). That means:
```php
Route::group(['middleware' => ['role:admin,access_backend']], function () {
    //
});
```
instead of
```php
Route::group(['middleware' => ['hasRoles'], 'roles' => 'Admin'], function () {
    //
});
```
What do you think?

Great work, guys. 
Cheers!

**Comment by Darival** [comment]
Hi @tabacitu,

(A) These are features that I'll be using and I'm sure a many people need something like these on their projects, so I thing they will made a good addition to the package.
(B) I like the middleware sintax on spatie/permissionmanager, I should have used it from the beginning.

best regards.

**Comment by OwenMelbz** [comment]
Personally I've come from using a bespoke CMS that has very flexible and granular permissions, so my ideal scenario would reflect that, which is what I've been trying to replicate, however I've come across a bigger issue which in my opinion would hamper user/developer experience.

Regards to using the middleware my concerns are that since Laravel 5.3 and the fact you can no longer access the session/auto in the construct - that the crud definition/fields/columns need to be moved first due to the following scenario 

Consider this ->

Role Admin
Role Team Member

Both of these have access to the CMS. 

Admins can access the user module, and check a box that defines if the user is an admin or not. They can do this because within the user construct, it defines. Field called is_admin thus it appears on the create/update view

However when the Team Member accesses the user module and edits a user, they also get the is_admin field, as it's defined. However we do not want them to have this. Which means I can only see 3 solutions, without migrating from the construct in 5.3.

1. duplicate the crud resource and call it like UserForRoleName and duplicate everything 
2. Within the construct instantly wrap it within another middleware to make sure you access Auth:user which intern allows you to wrap a 'if ( $user-hasPermission('update.admins') ) around a field, to make sure it only shows for that permission group 
3. Add extra validation in once a permission/role check has been completed in the request files, however this leaves the front end polluted with a field that cannot be used :(

For me, the above functionality is vital, and. I'm currently using additional middleware within e construct, which isn't ideal.

So that's my concerns about permissions, I think to create something that is truly versatile for all use cases then this sort of flexibility is a must, myself I don't know the best way to do this, as as a whole I'm more of a UX Developer than Laravel expert! But I'll happily make suggestions and brainstorm the best ways to do things as would love to help out with an open source project, as have loads of ideas, just not the Laravel/composer knowledge to be able to submit pull requests easily without guidance!

Thanks :)

**Comment by tabacitu** [comment]
Hi @OwenMelbz ,

I've been letting this sink for a while now. I think you're right. Those middleware are good and will be really easy to use for most use cases, where you want to block/allow access to an entire admin panel. It's a very Laravel-way to do things and that's good. But it's not granular enough for some use cases. This is a major issue for the way we define fields, columns and other CRUD functionalities and we should find a solution.

But so far, the only one I've come up with is having the definition in a separate controller method. Let's call is ```setupCrud()```. We would then call that method at the top of each CrudController method that has a route.

So CrudController will be something like:

```php
<?php

namespace Backpack\CRUD\app\Http\Controllers;

class CrudController extends BaseController
{
    use DispatchesJobs, ValidatesRequests;

    public $data = [];
    public $crud;

    public function setupCrud()
    {
        $this->crud = new CrudPanel();
    }

    public function index()
    {
        $this->setupCrud();
        // everything else that happened here
    }

    public function create()
    {
        $this->setupCrud();
        // everything else that happened here
    }

    public function storeCrud(StoreRequest $request = null)
    {
        $this->setupCrud();
        // everything else that happened here
    }

    public function edit($id)
    {
        $this->setupCrud();
        // everything else that happened here
    }

    public function updateCrud(UpdateRequest $request = null)
    {
        $this->setupCrud();
        // everything else that happened here
    }

    public function show($id)
    {
        $this->setupCrud();
        // everything else that happened here
    }

    public function destroy($id)
    {
        $this->setupCrud();
        // everything else that happened here
    }

    public function reorder()
    {
        $this->setupCrud();
        // everything else that happened here
    }

    public function saveReorder()
    {
        $this->setupCrud();
        // everything else that happened here
    }

    public function showDetailsRow($id)
    {
        $this->setupCrud();
        // everything else that happened here
    }

    public function search()
    {
        $this->setupCrud();
        // everything else that happened here
    }
}

```

and the controller for an entity, let's call it Test, will look something like this:

```php
<?php namespace App\Http\Controllers\Admin;

use Backpack\CRUD\app\Http\Controllers\CrudController;

// VALIDATION: change the requests to match your own file names if you need form validation
use App\Http\Requests\TestRequest as StoreRequest;
use App\Http\Requests\TestRequest as UpdateRequest;

class TestCrudController extends CrudController {

	private function setupCrud() {
        /*
		|--------------------------------------------------------------------------
		| BASIC CRUD INFORMATION
		|--------------------------------------------------------------------------
		*/
        $this->crud->setModel("App\Models\Test");
        $this->crud->setRoute("admin/test");
        $this->crud->setEntityNameStrings('test', 'tests');

        /*
		|--------------------------------------------------------------------------
		| BASIC CRUD INFORMATION
		|--------------------------------------------------------------------------
		*/

		// ------ CRUD FIELDS
        $this->crud->addField([
            'type' => 'text',
            'name' => 'name',
            'label' => 'File name',
            'prefix' => "<i class='fa fa-file'></i>",
        ]);
        $this->crud->addField([
            'type' => 'number',
            'name' => 'sum',
            'label' => 'Sum',
            'prefix' => "$",
            'suffix' => ".00"
        ]);
        $this->crud->addField([
            'type' => 'image',
            'name' => 'image',
            'label' => 'Upload image',
            // 'aspect_ratio' => 1,
            'crop' => true,
            'upload' => true
        ]);
        $this->crud->addField([
            'type' => 'upload_multiple',
            'name' => 'photos',
            'label' => 'Photos',
            'upload' => true
        ]);

        // ------ CRUD COLUMNS
        $this->crud->addColumn([
            'type' => 'text',
            'name' => 'name',
            'label' => 'Name'
        ]); // add a single column, at the end of the stack
        $this->crud->addColumn([
            'type' => 'text',
            'name' => 'sum',
            'label' => 'Sum'
        ]); // add a single column, at the end of the stack
        $this->crud->addColumn([
            'type' => 'text',
            'name' => 'image',
            'label' => 'Image path'
        ]); // add a single column, at the end of the stack
        $this->crud->addColumn([
            'type' => 'array',
            'name' => 'photos',
            'label' => 'Photos'
        ]); // add a single column, at the end of the stack
    }

	public function store(StoreRequest $request)
	{
		return parent::storeCrud();
	}

	public function update(UpdateRequest $request)
	{
		return parent::updateCrud();
	}
}

```

What I like about this: 
- the only difference for the developer would be that he needs to rename where he defines the CRUD from ```__construct()``` to ```setupCrud()```;
- it frees up the ```__construct()``` for the developer to do whatever he wants in it;

What I don't like about this:
- I don't think we can achieve this without a breaking change; I mean we can, by having ```$this->crud = new CrudPanel();``` both in the constructor and in ```setupCrud()```, but that would be hacky;

Any other ideas? Solutions to this backwards-compatibility issue?

**Comment by abrahampe** [comment]
Why there is no index() method in the PermissionManager controllers? I tried to extend them to use the middleware as suggested above, but this stopped me. Any workaround?

**Comment by tabacitu** [comment]
Since the setup() method has been implemented a long time ago, I'm going to close this issue. 

For anyone reading this in search for a solution, in your EntityCrudController just rename your ```__construct()``` to ```setup()```. That will now allow you to use the session, the request, etc.

Cheers!
