### ISSUE TITLE
A Little more instructions for Role and Permission CRUD is needed.

### ISSUE THREAD

**Issue by chriscalip** [Laravel-Backpack/PermissionManager#141]
Models: `Spatie\Permission\Models\Role` and `Spatie\Permission\Models\Permission`
does not have `use Backpack\CRUD\CrudTrait;` 

a little bit more instructions is needed for this situation.

**Comment by tabacitu** [comment]
Hi @chriscalip ,

Indeed. They don't have CrudTrait. That's why this package uses its own models... Any models you create to customize this should extend the **Backpack** models, NOT the **Spatie** models.

Cheers!
