### ISSUE TITLE
Duplicating User Admin

### ISSUE THREAD

**Issue by justjeremy70** [Laravel-Backpack/PermissionManager#143]
Latest and greatest version of everything backpack and laravel as of today's date.
**This is not a bug.**

I would like to know what you think would be the best way to duplicate the user admin to its own model/controllers/views?

I'm working on a project where group admin can edit people that are within their same group. I don't want to give them full access to the full back-end admin area.  I've already figured out how to just bring back all the users within the group via db calls and display them.  However, I really like your use of the datatables and search functionality.

TIA!

**Comment by tabacitu** [comment]
@justjeremy70 in the UserCrudController, you could do something use ```$this->crud->addClause()``` to only show certain entries. Check out ["advanced queries" here](https://laravel-backpack.readme.io/docs/crud-full-api#section-often-used).

Of course, for that to work you'd need to first [overwrite the routes](https://github.com/Laravel-Backpack/PermissionManager#overwriting-functionality) and point to your own UserCrudController, that extends the one in the package.

Hope it helps.
Cheers!
