### ISSUE TITLE
getting Your requirements could not be resolved to an installable set of packages error

### ISSUE THREAD

**Issue by harishdurga** [Laravel-Backpack/PermissionManager#149]
# Bug report

### What I did:
i ran the following command
 composer require backpack/permissionmanager

### What happened:
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for spatie/laravel-permission (locked at 2.9.2, required as ^2.9) -> satisfiable by spatie/laravel-permission[2.9.2].
    - backpack/permissionmanager 2.1.0 requires spatie/laravel-permission ^1.4 -> satisfiable by spatie/laravel-permission[v1.x-dev].
    - backpack/permissionmanager 2.1.1 requires spatie/laravel-permission ^1.4 -> satisfiable by spatie/laravel-permission[v1.x-dev].
    - backpack/permissionmanager 2.1.10 requires spatie/laravel-permission ^1.4 -> satisfiable by spatie/laravel-permission[v1.x-dev].
    - backpack/permissionmanager 2.1.11 requires spatie/laravel-permission ^1.4 -> satisfiable by spatie/laravel-permission[v1.x-dev].
    - backpack/permissionmanager 2.1.12 requires spatie/laravel-permission ^1.4 -> satisfiable by spatie/laravel-permission[v1.x-dev].
    - backpack/permissionmanager 2.1.13 requires spatie/laravel-permission ^1.4 -> satisfiable by spatie/laravel-permission[v1.x-dev].
    - backpack/permissionmanager 2.1.14 requires spatie/laravel-permission ^1.4 -> satisfiable by spatie/laravel-permission[v1.x-dev].
    - backpack/permissionmanager 2.1.15 requires spatie/laravel-permission ^1.4 -> satisfiable by spatie/laravel-permission[v1.x-dev].
    - backpack/permissionmanager 2.1.16 requires spatie/laravel-permission ^1.4 -> satisfiable by spatie/laravel-permission[v1.x-dev].
    - backpack/permissionmanager 2.1.17 requires spatie/laravel-permission ^1.4 -> satisfiable by spatie/laravel-permission[v1.x-dev].
    - backpack/permissionmanager 2.1.18 requires spatie/laravel-permission ^1.4 -> satisfiable by spatie/laravel-permission[v1.x-dev].
    - backpack/permissionmanager 2.1.19 requires spatie/laravel-permission ^1.4 -> satisfiable by spatie/laravel-permission[v1.x-dev].
    - backpack/permissionmanager 2.1.2 requires spatie/laravel-permission ^1.4 -> satisfiable by spatie/laravel-permission[v1.x-dev].
    - backpack/permissionmanager 2.1.20 requires spatie/laravel-permission ^1.4 -> satisfiable by spatie/laravel-permission[v1.x-dev].
    - backpack/permissionmanager 2.1.21 requires spatie/laravel-permission ^1.4 -> satisfiable by spatie/laravel-permission[v1.x-dev].
    - backpack/permissionmanager 2.1.22 requires spatie/laravel-permission ^1.4 -> satisfiable by spatie/laravel-permission[v1.x-dev].
    - backpack/permissionmanager 2.1.23 requires spatie/laravel-permission ^1.4 -> satisfiable by spatie/laravel-permission[v1.x-dev].
    - backpack/permissionmanager 2.1.24 requires spatie/laravel-permission ^1.4 -> satisfiable by spatie/laravel-permission[v1.x-dev].
    - backpack/permissionmanager 2.1.25 requires spatie/laravel-permission ^1.4 -> satisfiable by spatie/laravel-permission[v1.x-dev].
    - backpack/permissionmanager 2.1.26 requires spatie/laravel-permission ^1.4 -> satisfiable by spatie/laravel-permission[v1.x-dev].
    - backpack/permissionmanager 2.1.3 requires spatie/laravel-permission ^1.4 -> satisfiable by spatie/laravel-permission[v1.x-dev].
    - backpack/permissionmanager 2.1.4 requires spatie/laravel-permission ^1.4 -> satisfiable by spatie/laravel-permission[v1.x-dev].
    - backpack/permissionmanager 2.1.5 requires spatie/laravel-permission ^1.4 -> satisfiable by spatie/laravel-permission[v1.x-dev].
    - backpack/permissionmanager 2.1.6 requires spatie/laravel-permission ^1.4 -> satisfiable by spatie/laravel-permission[v1.x-dev].
    - backpack/permissionmanager 2.1.7 requires spatie/laravel-permission ^1.4 -> satisfiable by spatie/laravel-permission[v1.x-dev].
    - backpack/permissionmanager 2.1.8 requires spatie/laravel-permission ^1.4 -> satisfiable by spatie/laravel-permission[v1.x-dev].
    - backpack/permissionmanager 2.1.9 requires spatie/laravel-permission ^1.4 -> satisfiable by spatie/laravel-permission[v1.x-dev].
    - Conclusion: don't install spatie/laravel-permission v1.x-dev
    - Installation request for backpack/permissionmanager ^2.1 -> satisfiable by backpack/permissionmanager[2.1.0, 2.1.1, 2.1.10, 2.1.11, 2.1.12, 2.1.13, 2.1.14, 2.1.15, 2.1.16, 2.1.17, 2.1.18, 2.1.19, 2.1.2, 2.1.20, 2.1.21, 2.1.22, 2.1.23, 2.1.24, 2.1.25, 2.1.26, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.1.7, 2.1.8, 2.1.9].

Installation failed, reverting ./composer.json to its original content.

### Backpack, Laravel, PHP, DB version:
1.1, 5.6, 7.2.2, mysql 5.7

**Comment by tabacitu** [comment]
Hi @harishdurga ,

Seems like you're already using spatie/laravel-permission version 2.9, which is not supported by PermissionManager yet. You can either install an earlier version of laravel-permission, or create a CRUD for it yourself - the code in this package should cover 90% of the functionality.

Cheers!
