### ISSUE TITLE
Permissions on routes used for select2_from_ajax

### ISSUE THREAD

**Issue by bilfeldt** [Laravel-Backpack/PermissionManager#152]
How one can add middleware to authenticate Admin API calls made from [select2_from_ajax](https://laravel-backpack.readme.io/docs/crud-fields#section-select2_from_ajax) fields?

It does not work adding the middleware ```admin``` nor does it work adding the middleware ```can:permission``` where ```permission``` is the permission we are testing for.

**Comment by bilfeldt** [comment]
This is not a bug, but I suggest adding this to the usage guide.

**Comment by tabacitu** [comment]
Hi @bilfeldt ,

We just added support for ```backpack_middleware()``` in this package. A ```composer update``` should do it for you. I don't quite get what you're trying to achieve, but:
- you should be able to add a middleware to the ```base.php``` config file and it will use it in this package too;
- you can overwrite the routes for this package by creating a ```routes/backpack/permissionmanager.php``` file; then Backpack will pick that one up, instead of the one in the package;

Hope it helps.
Cheers!

**Comment by bilfeldt** [comment]
@tabacitu: Thanks, we will take a look at `backpack_middleware()`.

What we are trying to achieve, and suggest adding a description for, is that when implementing [select2_from_ajax](https://laravel-backpack.readme.io/v3.4/docs/crud-fields#section-select2_from_ajax) then we are told to implement

> a controller and routes for the data_source

which is used by CRUD when fetching related resources. But it says nothing about how we can restrict access to these routes. This could be by adding the `admin` middleware or alternatively adding the `can:category` middleware in case we are looking for categories like in the example:
```
Route::get('/api/category', 'Api\CategoryController@index');
Route::get('/api/category/{id}', 'Api\CategoryController@show');
```
but none of this seems to work. So I am wondering what kind of authentication is used by Backpack when making these AJAX api calls.

**Comment by tabacitu** [comment]
Hmm... I think I understand now.

Restricting access to the API calls can be done like any other Laravel API - most commonly using middleware, in route definition or in the controller. Nothing special about them.

Backpack will make plain old AJAX calls, nothing special about them either. 

Usually it's a good idea to place the routes behind the same middleware as the CRUD itself. So for a Product you'd have something like:

```php
Route::group([
    'prefix'     => config('backpack.base.route_prefix', 'admin'),
    'middleware' => [backpack_middleware()],
    'namespace'  => 'Admin',
], function () {
    CRUD::resource('product', 'ProductCrudController');
    // ---------------------------
    // I'd add the API routes here
    // So that they'd be accessible to the same users
    // ---------------------------
    Route::get('api/article', 'Api\ArticleController@index');
    Route::get('api/article/{id}', 'Api\ArticleController@show');
});
```

But again - this isn't something that's Backpack-specific, just the way Laravel works. The ```select2_from_ajax``` field will just make HTTP calls to an endpoint you specify, the same thing that you can get by calling that URL in the address bar. The instructions on how to create the API are just a fast way to get something working, but there are plenty other ways, depending on your needs.
