### ISSUE TITLE
Method Illuminate\Database\Query\Builder::translationEnabled does not exist

### ISSUE THREAD

**Issue by imansugirman** [Laravel-Backpack/PermissionManager#154]
# Bug report
Error when click user menu

### What happened:
Method Illuminate\Database\Query\Builder::translationEnabled does not exist

### Backpack, Laravel, PHP, DB version:
"backpack/crud": "^3.4",
"backpack/permissionmanager": "^2.1",
"laravel/framework": "5.6.*",
"laravel/tinker": "^1.0"
PHP : 7.2
Mysql : 5.7

![jepretan layar 2018-06-07 pada 19 57 37](https://user-images.githubusercontent.com/38036171/41101004-101943ac-6a8d-11e8-848a-104b9a7690fe.png)

**Comment by tabacitu** [comment]
Hi @imansugirman ,

My first guess:
- you haven't put a ```uses CrudTrait;``` on your ```User``` model, like the docs say;

Am I right?

**Comment by imansugirman** [comment]
Ah ok. i'm forget it. thanks @tabacitu
