### ISSUE TITLE
Spatie API is not using config('backpack.base.user_model_fqn')

### ISSUE THREAD

**Issue by Darival** [Laravel-Backpack/PermissionManager#157]
# Bug report

### What I did:
Installed PermissionManager, and tried using the API in blade.php
```
@role('admin')
    always false 
@endrole
```
### What I expected to happen:
When using API:
```PHP
>>>User::first()->roles
=> Illuminate\Database\Eloquent\Collection {#2523
     all: [
       Backpack\PermissionManager\app\Models\Role {#2513
         id: 1,
         name: "admin",
         guard_name: "web",
         created_at: "2018-06-08 20:26:56",
         updated_at: "2018-06-08 20:26:56",
         pivot: Illuminate\Database\Eloquent\Relations\MorphPivot {#2525
           model_id: 1,
           role_id: 1,
           model_type: "App\User",
         },
       },
     ],
   }

```

### What happened:
```PHP
>>> User::first()->roles
=> Illuminate\Database\Eloquent\Collection {#2516
     all: [],
   }

```
### What I've already tried to fix it:
```PHP
>>> \Backpack\Base\app\Models\BackpackUser::first()->roles
=> Illuminate\Database\Eloquent\Collection {#2523
     all: [
       Backpack\PermissionManager\app\Models\Role {#2513
         id: 1,
         name: "admin",
         guard_name: "web",
         created_at: "2018-06-08 20:26:56",
         updated_at: "2018-06-08 20:26:56",
         pivot: Illuminate\Database\Eloquent\Relations\MorphPivot {#2525
           model_id: 1,
           role_id: 1,
           model_type: "Backpack\Base\app\Models\BackpackUser",
         },
       },
     ],
   }

```
in model_has_roles table, colum model_type should be App\User in order for the Spatie API to work
```
mysql> select * from model_has_roles;
+---------+---------------------------------------+----------+
| role_id | model_type                            | model_id |
+---------+---------------------------------------+----------+
|       1 | Backpack\Base\app\Models\BackpackUser |        1 |
+---------+---------------------------------------+----------+
```
### Backpack, Laravel, PHP, DB version:
Backpack/base: 0.9.6
Backpack/crud: 3.4.13
Backpack/permissionmanager: 3.12.0
laravel/framework: "5.6.*"
MySQL: 5.7.22

**Comment by Chnkr** [comment]
Happening here as well

**Comment by tabacitu** [comment]
@Darival , @Chnkr - thank you for telling me about this. 

Please change your ```config/auth.php``` to use ```Backpack\Base\app\Models\BackpackUser::class``` instead of ```App\User```;
```diff
    'providers' => [
        'users' => [
            'driver' => 'eloquent',
-            'model' => App\User::class,
+            'model' => Backpack\Base\app\Models\BackpackUser::class,
        ],

        // 'users' => [
        //     'driver' => 'database',
        //     'table' => 'users',
        // ],
    ],
```

This should fix it for you guys. I'll add this to the docs right now.

Cheers!

**Comment by mpixelz** [comment]
this works only if we are using single login session.. what about different sessions for admin and users?

**Comment by aguante** [comment]
Hey everyone!

@tabacitu shouldn't the config/auth.php use `App\Models\BackpackUser::class` instead of `Backpack\Base\app\Models\BackpackUser::class`, which is the vendor class?

Best,
Javier

**Comment by roberto-butti** [comment]
Same issue.
It seems solved now, i'm going to explain what I did.

In the `config/backpack/base.php` I set:
`  'user_model_fqn' => App\Models\BackpackUser::class,`
as mentioned in laravelbackpack base 3.5 upgrade documentation step 3
https://backpackforlaravel.com/docs/3.5/upgrade-guide#step-3


I set the same Model Class in _config/auth.php_ for the provider for eloquent driver
```
    'providers' => [
        'users' => [
            'driver' => 'eloquent',
            //'model' => App\User::class,
            'model' => App\Models\BackpackUser::class,
```


You need also to check the value for the _model_type_ column in the _model_has_roles_ table and _model_type_ in the _model_has_permissions_ table. The value in this columns needs to be : App\Models\BackpackUser (like model in providers and user_model_fqn in base).
