### ISSUE TITLE
Delete version 2.12.0 from Packagist

### ISSUE THREAD

**Issue by FrittenKeeZ** [Laravel-Backpack/PermissionManager#158]
In short: sites will break when running `composer update` due to the `^2.1` requirement most have in their `composer.json` file.
https://packagist.org/packages/backpack/permissionmanager#2.12.0

**Comment by tabacitu** [comment]
You're totally right @FrittenKeeZ  . That was a tagging name error - my fault. I thought deleting it from Github would auto-update Packagist too, but it looks like it doesn't. Thank you, I just deleted it from Packagist too.

Thanks again, cheers!
