### ISSUE TITLE
Call to undefined method Illuminate\Database\Query\Builder::addFakes()

### ISSUE THREAD

**Issue by chiqui3d** [Laravel-Backpack/PermissionManager#16]
I installed Permission Manager and when you access the Administrator -> users, I get the following error:

`BadMethodCallException in Builder.php line 2431:
Call to undefined method Illuminate\Database\Query\Builder::addFakes()`

The roles and permissions pages work well , the only one that does not work, it is the users.

I hope you can help me.
Regards!!

**Comment by chiqui3d** [comment]
Ready, I forgot to add the namespace in /App/User.php

**Comment by tabacitu** [comment]
Glad you figured it out. Cheers!

**Comment by bauersfeld** [comment]
Has this been resolved?

**Comment by tabacitu** [comment]
Later note: this error usually happens when you forgot to add CrudTrait on the model (or, like it happened above, its namespace).

Cheers!

**Comment by nathanh0** [comment]
@tabacitu CrudTrait fixed my version of this error. Thank you for always posting the way to fix things, it's rare for me to find immediate answers on my first search for this error.

**Comment by nathanh0** [comment]
````
<?php

namespace App\MCE\Project\Database\Eloquent;

use Backpack\CRUD\CrudTrait;  # This wasn't here, added it and it worked.
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Project extends Model {

    use SoftDeletes;
    use CrudTrait;   # This wasn't here, added it and it worked.

````
