### ISSUE TITLE
handlePasswordInput(CrudRequest $request)

### ISSUE THREAD

**Issue by roberto-butti** [Laravel-Backpack/PermissionManager#161]
# Bug report

### What I did:
Saving a user from the CRUD

### What I expected to happen:
The user is saved

### What happened:
`Argument 1 passed to Backpack\PermissionManager\app\Http\Controllers\UserCrudController::handlePasswordInput() must be an instance of Backpack\CRUD\app\Http\Requests\CrudRequest, instance of Backpack\PermissionManager\app\Http\Requests\UserUpdateCrudRequest given,`

### What I've already tried to fix it:
In UserCrudController change from 
protected function handlePasswordInput(CrudRequest $request)
to
protected function handlePasswordInput(UpdateRequest $request)

### Backpack, Laravel, PHP, DB version:
Backpackpermission 3.12.2

**Comment by tabacitu** [comment]
Thank you for reporting this - AND @nathanphelps for providing a solution. Just merged and tagged the PR - a ```composer update``` should fix it for you.

Cheers!
