### ISSUE TITLE
hasPermissionTo return False, even if the permission on the database exists 

### ISSUE THREAD

**Issue by xdasty** [Laravel-Backpack/PermissionManager#165]
# Bug report
hasPermissionTo return False, even if the permission on the database exists 

### What I did:
----------------------------------------------------------------------------------
AppServiceProviders.php
------------------------------------------
namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Illuminate\Support\Facades\Blade;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

use Illuminate\View\Compilers\BladeCompiler;

    public function register()
    {
        $this->app->afterResolving('blade.compiler', function (BladeCompiler $bladeCompiler) {
            $bladeCompiler->directive('haspermission', function ($permission) {
               list($module, $guard) = explode(',',$permission);
                return "< ?php if(auth()->check() && auth()->user()->hasPermissionTo({$module},{$guard})): ? >";
            });

            $bladeCompiler->directive('endhaspermission', function () {
                return '<?php endif; ?>';
            });
        });
    }
------------------------------------------

sidebar.blade.php
---------------------------------------------
@haspermission('menu1', 'admin')
Hello World :-)
@endhaspermission
---------------------------------------------

----------------------------------------------------------------------------------

### What I expected to happen:

permission exists in the database, but:
auth()->check() -> return True
auth()->user()->hasPermissionTo({$module},{$guard}) ->return True

### What happened:

auth()->check() -> return True
auth()->user()->hasPermissionTo({$module},{$guard}) ->return False

### What I've already tried to fix it:
------------------------------------------------------

Update:

HasPermissions.php

call function hasPermissionTo
-- $this->hasDirectPermission($permission)  -- return False (OK)
-- $this->hasPermissionViaRole($permission) -- return False  (NO the permission via Role Exist)

call hasPermissionViaRole
-- $permission->roles  -- return object 'items' =>  Role (OK Find Role)
-- $this->hasRole($permission->roles) -- return False (NO the Role Exist)
------------------------------------------------------

### Backpack, Laravel, PHP, DB version:
Laravel Framework   		5.6.26
backpack/backupmanager		1.4.2
backpack/base			0.9.6 
backpack/crud			3.4.18
backpack/generators		1.2.2
backpack/langfilemanager	1.0.25
backpack/logmanager		2.3.21
backpack/newscrud		2.1.6
backpack/pagemanager		1.1.23
backpack/permissionmanager	3.12.4
backpack/settings		2.1.0
spatie/laravel-permission             2.12.2
barryvdh/elfinder-flysystem-driver	v0.2.1
barryvdh/laravel-debugbar		v3.1.5
barryvdh/laravel-elfinder		v0.3.12

PHP 7.2.1
Mysql 5.7.21

**Comment by xdasty** [comment]
I solved

I had to change:
config/auth.php

-            'model' => App\User::class,
+            'model' => Backpack\Base\app\Models\BackpackUser::class,

**Comment by tabacitu** [comment]
Thank you for reporting this, and providing your solution, @xdasty . For future reference, this will be fixed in Backpack\Base soon, when this PR gets merged - https://github.com/Laravel-Backpack/Base/pull/323

Thank you!
