### ISSUE TITLE
Blade directives not working with BackpackUser class

### ISSUE THREAD

**Issue by Evanslooten** [Laravel-Backpack/PermissionManager#166]
# Bug report

### What I did:
Changed the user model in the "Providers" section in config/auth.php to Backpack\Base\app\Models\BackpackUser::class (from default App\User::class) as specified in the setup instructions
### What I expected to happen:
Everything to work as it was with the App\User class
### What happened:
Blade directive fails (loads @else condition) when otherwise loads correctly with base User class
### What I've already tried to fix it:
Reverted to the base Laravel App\User class
### Backpack, Laravel, PHP, DB version:
"backpack/base": "^0.9.0",
"backpack/crud": "^3.4",
"backpack/permissionmanager": "^3.12",
PHP 7.1
MySQL 5.7

**Comment by tabacitu** [comment]
Hi @Evanslooten ,

Sorry for the late reply - this package is considered more of an example then a "use-as-is", so it was difficult to get to its issues.

I've spent some time on this and gotten to the root problem. The fix will not be in ```Backpack\PermissionManager``` but in ```Backpack\Base```. Here's the PR for it, which will get merged shortly - https://github.com/Laravel-Backpack/Base/pull/323 (I hope).

Let me know what you think - and reopen the issue if I'm mistaken and this doesn't fix it.

Thanks, cheers!
