### ISSUE TITLE
Using your own model with PermissionManager

### ISSUE THREAD

**Issue by niladam** [Laravel-Backpack/PermissionManager#167]
I really like the packaged, as it provides my colleagues with an easy interface that allows them to change/edit the roles/permissions.

However i wanted to use my *own* model with it. I was seeding the database for the initial users (using `firstOrCreate`) and for some reason, the roles and permissions were being created but the roles were not being attached to the user.

After a little debugging and some exchange of ideas in the gitter room, i managed to figure it out.

In `UserCrudController` the model is being set as below:

```php
$this->crud->setModel(config('backpack.base.user_model_fqn'));
```

This made me realise that i had to change my `config/backpack/base.php` file and change the key **user_model_fqn** to my class. Specifically it looks like this now:

```php
'user_model_fqn' => \App\User::class,
```

I just figured i should post this for anyone looking for the same thing and i think this could also be added to the docs :) -- right @tabacitu ?:)

**Comment by lucasdcrk** [comment]
Thanks for sharing this, but if you set your model to the default user model you can't edit your account on the admin panel, any idea why?

**Comment by niladam** [comment]
@lucasdcrk @tabacitu - i agree -- this could be in the docs :)

**Comment by tabacitu** [comment]
Yup, you're totally right, thank you for writing about this @niladam . I've just [added this to the documentation](https://backpackforlaravel.com/docs/3.4/base-how-to#use-your-own-user-model-instead-of-backpackuser).

Thanks. Cheers!

**Comment by happygrizzly** [comment]
Hey, what are the cons/pros of staying with the original user model? Is it only password resets functionality that is added by the BackpackUser? 

What if I stripped off email verification, password resets (I left the original table tough) functionality for the public part of the app, will Backpack function normally?
