### ISSUE TITLE
Method Illuminate\Database\Query\Builder::translationEnabled does not exist.

### ISSUE THREAD

**Issue by TheAngelM97** [Laravel-Backpack/PermissionManager#168]
# Bug report
Method Illuminate\Database\Query\Builder::translationEnabled does not exist.

### What I did:
I followed the instructions on installing it and tried to open the "create permission" page

### What I expected to happen:
To open a form in which I can add permissions

### What happened:
I got exception

### What I've already tried to fix it:
I don't know what to do

### Backpack, Laravel, PHP, DB version:
Backpack: 3.4, Laravel 5.6, PHP 7.1.8

**Comment by tabacitu** [comment]
Hi @TheAngelM97 ,

Sorry to be so late to reply - the issue has long been fixed though. A ```composer update``` should fix it for you.

Cheers!
