### ISSUE TITLE
Cannot get $user->roles and $user->permissions

### ISSUE THREAD

**Issue by doncadavona** [Laravel-Backpack/PermissionManager#169]
# Bug report

Cannot get `$user->roles` and `$user->permissions`.

### What I did:

Installed PermissionManager, and added some roles, permissions, users and assigned them with roles. But when I `$user->roles` and `$user->permissions.`, they return empty Collections (`Illuminate\Database\Eloquent\Collection`).

All users have roles. But with `\App\User::with('roles')->get()`, relations attribute returns empty Collection.

### What I expected to happen:

`$user->roles` and `$user->permissions.` should return a Collection of Role and Permission.

### What happened:

`$user->roles` and `$user->permissions.` returns empty Collection.

### What I've already tried to fix it:

Nothing yet. But read and suspect that change in Spatie's schema caused some bugs in the Eloquent models.
For now downgrading to `backpack/permissionmanager ^2.1` solved it.

### Backpack, Laravel, PHP, DB version:

Backpack CRUD: `3.4`
Laravel: `5.6`
PHP: `7.2.2`
DB: `5.7.21`

**Comment by doncadavona** [comment]
Thank you for responding @AbbyJanke , I see, but I suppose we should be able to get the a Collection of Role(s) via `$user->roles` because the new schema uses polymorphic design that should allow such operation. I wonder there is even a need for `$user->getRoleNames()`? Shouldn't be `$user->roles->pluck('name')` enough? Sorry, I think this is a Spatie issue.

**Comment by tabacitu** [comment]
Hi @doncadavona , @AbbyJanke ,

Sorry for the late reply - this package is considered more of an example then a "use-as-is", so it was difficult to get to its issues.

I've spent some time on this and gotten to the root problem. The fix will not be in ```Backpack\PermissionManager``` but in ```Backpack\Base```. Here's the PR for it, which will get merged shortly - https://github.com/Laravel-Backpack/Base/pull/323 (I hope).

Let me know what you think - and reopen the issue if I'm mistaken and this doesn't fix it.

Thanks, cheers!
