### ISSUE TITLE
Undefined index : dependencies

### ISSUE THREAD

**Issue by kev-ian** [Laravel-Backpack/PermissionManager#17]
Hi,

Using the PermissionManager, i'm getting the following error while trying to add a user

Undefined index: dependencies (View:  /resources/views/vendor/backpack/crud/fields/checklist_dependency.blade.php) 

Can someone help?

**Comment by tabacitu** [comment]
Hi @kev-ian ,

That's odd. Just tried and it works for me.

What version of PermissionManager are you using? You can find that by going to vendor/backpack/permissionmanager/changelog.md

Thanks!

**Comment by kev-ian** [comment]
Hi @tabacitu , im using version 2.1.3

**Comment by tabacitu** [comment]
And do you have any roles & permissions added?

**Comment by kev-ian** [comment]
I just added a role and a permission in the database. Still same error

**Comment by kev-ian** [comment]
In file /resources/views/vendor/backpack/crud/fields/checklist_dependency.blade.php, 

The key 'depencies' is not present in the $field array ! Maybe that's what causing the issue?

**Comment by tabacitu** [comment]
Oh, I understand. I think a ```composer update``` should fix it for you.

**Comment by tabacitu** [comment]
Did it fix it? :-)
