### ISSUE TITLE
BackpackUser::class don't exist

### ISSUE THREAD

**Issue by gaiapuffo** [Laravel-Backpack/PermissionManager#170]
Hi,

try to insert permission manager in my laravel backpack application.
I read the guide but I have a problem when I make            

 'model' => Backpack\Base\app\Models\BackpackUser::class,

Because there isn't this class in my application
When i make 

composer require backpack/permissionmanager:2.1.26

not create BackpackUser::class, so I have an error

**Comment by tabacitu** [comment]
Hi @gaiapuffo ,

I suspect you were using an old version of Backpack\Base, so a ```composer update``` before installing PermissionManager should have fixed it for you.

Sorry for the late reply.

Cheers!
