### ISSUE TITLE
Update User don't validate e-mail unique

### ISSUE THREAD

**Issue by vw1302** [Laravel-Backpack/PermissionManager#173]
# Bug report

### What I did:
Update user e-mail to an e-mail, that already existes
### What I expected to happen:
"email taken' message
### What happened:
"SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'test@example.com' for key 'users_email_unique' (SQL: update `users` set `email` = test@example.com, `updated_at` = 2018-08-30 10:05:22 where `id` = 2) "
### What I've already tried to fix it:
override update method in UserCrudController and add
```
        $request->validate([
            'email'    => 'required|unique:'.config('permission.table_names.users', 'users').',email,'.$request->all()['id'],
            'name'     => 'required',
            'password' => 'confirmed',
        ]);
```

### Could be fixed in:
UserUpdateCrudRequest
change 
```
    public function rules()
    {
        return [
            'email'    => 'required',
            'name'     => 'required',
            'password' => 'confirmed',
        ];
    }
```
to something like
```
    public function rules()
    {
        return [
            'email'    => 'required|unique:'.config('permission.table_names.users', 'users').',email,'.$this->get('id'),
            'name'     => 'required',
            'password' => 'confirmed',
        ];
    }
```

**Comment by tabacitu** [comment]
You're totally right! Thank you @vw1302  for noticing and providing a solution for this oversight. Just applied your solution here https://github.com/Laravel-Backpack/PermissionManager/commit/6965dd05ea539565dac9489254e78657b5415c64 - so ```composer update``` should fix it for you.

Thanks again. Cheers!
