### ISSUE TITLE
Question about backpack_url('user')

### ISSUE THREAD

**Issue by jackfruhecolab** [Laravel-Backpack/PermissionManager#174]
# Bug report
This is probably not a bug, just something I don't yet understand...

I originally installed the user management package https://github.com/eduardoarandah/UserManager
That was working fine for basic user editing.

Then I installed this permissionmanager package.
It appears to be working, but it looks like `backpack_url('user')` still points to the orignal package.
The other two suggested urls work great (roles and permissions)

I suspect the new user crud works great too, I just can't find it.

Any ideas on where to look? Where does a backpack URL get defined?

Thanks!

- Jack

**Comment by tabacitu** [comment]
If you have both packages installed, they may be using the same route - so only the last registered route will be available to you. Uninstall eduardoarandah/UserManager using composer and it should work ;-)

Hope it helps. Cheers!
