### ISSUE TITLE
Must use Backpack\Base\app\Models\BackpackUser and not App\Models\User

### ISSUE THREAD

**Issue by Patabugen** [Laravel-Backpack/PermissionManager#175]
# Bug report

### What I did:
Created a database seeder which creates a user and some roles and assigns them.

### What I expected to happen:
I expected the created user to already have the created roles.

### What happened:
The user and roles get created without an issue but the role is not properly assigned to the user.

It's not clear (or documented anywhere) that I should be using `Backpack\Base\app\Models\BackpackUser` and not `App\Models\User` when retrieving users (if I want permissions to work).

E.g.:
```
$user = \App\Models\User::where('email', 'admin@example.com');
$adminRole = Role::findOrCreate('admin');
$user->assignRole($adminRole);
```

Creates a row in `model_has_roles` saying "App\Models\User has role 1".

However the middleware/CRUD/everything else wants `model_has_rows_ to say "Backpack\Base\app\Models\BackpackUser has role 1"

This one works:
```
$user = \Backpack\Base\app\Models\BackpackUser::where('email', 'admin@example.com');
$adminRole = Role::findOrCreate('admin');
$user->assignRole($adminRole);
```

### What I've already tried to fix it:
I've changed my seeder to use `Backpack\Base\app\Models\BackpackUser` and it is now working as expected. However I think either the documentation should be updated, or if I'm mis-understanding how things are working please explain.

### Backpack, Laravel, PHP, DB version:
Backpack 3.4
Backpack Permissions: 3.12
Laravel: 5.6
PHP: 7.1

**Comment by tabacitu** [comment]
Hi @Patabugen ,

You're right, thank you, we'll update the docs. Even better would be to use ```config('backpack.base.user_model_fqn')```, so that if you ever change it, it'll change too. Something like this would be ideal, I think:

```php
$userModel = config('backpack.base.user_model_fqn');
$userModel = new $userModel;
$user = $userModel->where(...);
```

Cheers!
