### ISSUE TITLE
Blade Directive still not working

### ISSUE THREAD

**Issue by josefhaydn** [Laravel-Backpack/PermissionManager#179]
# Bug report

The blade directives should be working since update to Backpack Base 1.0.0,
but they are not.
The blade directives are working without problems in the backpack-demo
project, but this is based on older versions of Backpack packages.

### What I did:
This does not work:

@role('admin')
    Hello Admin!
@else
    Hello Non-Admin!
@endrole

### What I expected to happen:
Discrimination according to directive.
### What happened:
No discrimination.
### What I've already tried to fix it:

This works, but it is a workaround:

@if (backpack_auth()->user()->hasRole('superuser'))
         Hello Admin!
@else
         Hello Non-Admin!
@endif

### Backpack, Laravel, PHP, DB version:
       "php": "^7.1.3",
        "backpack/base": "^1.0",
        "backpack/crud": "^3.5",
        "backpack/permissionmanager": "^3.12",
        "laravel/framework": "5.7.*",
        "laravel/tinker": "^1.0"

**Comment by AbbyJanke** [comment]
Use lowercase on role.. its spatie permission that we use.

**Comment by josefhaydn** [comment]
Thank you for cour comment.
Unfortunately this is not the solution.
Somehow my code got changed when copying it to
this forum, so it is displayed in wrong capital letters above.
The true code in my program is written in correct capitalization.
When doing this in my program:

                @if (backpack_auth()->user()->hasRole('superuser'))
                    Hello Admin!
                @else
                    Hello Non-Admin!
                @endif
                @role('superuser')
                    Hello Admin!
                @else
                    Hello Non-Admin!
                @endrole
The output, when logged in with "superuser" role is
Hello Admin! (correct) followed by "Hello Non-Admin!"
(incorrect). So the blade directives do not work as intended.
This problem was mentioned in another issue report and
the programmer of Backpack answered he has solved it in
1.0.0 release. But at least on my 1.0.2 project it still is not
working.
Note, as I wrote above: In the backpack-demo project on github,
which is based on an older version of Backpack, the @role directives
are working correctly.

I do not really mind to write the longer if statement.
I mainly posted this issue to help others who might not know
what is going on.

Thanks.

**Comment by tabacitu** [comment]
Thanks for posting the issue @josefhaydn ! You're right, there was a problem with that in 1.0.0. 

However, in 1.0.2 (the version you're running), we've included a new middleware, ```UseBackpackAuthGuardInsteadOfDefaultAuthGuard```. This middleware, when applied, makes it that ```Auth``` returns the same thing as ```backpack_auth()```, so it will make the ```@role``` handle work. You can use it on all Backpack pages by adding it to your ```config/backpack/base.php``` file:

```diff
    // The classes for the middleware to check if the visitor is an admin
    // Can be a single class or an array of clases
    'middleware_class' => [
        App\Http\Middleware\CheckIfAdmin::class,
        \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
+       Backpack\Base\app\Http\Middleware\UseBackpackAuthGuardInsteadOfDefaultAuthGuard::class,
    ],
```

But it's not a very intuitive workaround, so I recommend you also read details about it here (Option E), to know all the implications: https://github.com/Laravel-Backpack/PermissionManager/issues/177#issuecomment-442716633

Cheers!

**Comment by kiddtang** [comment]
@tabacitu 

Still using Laravel 5.5 LTS, however the permissionmanager is able to install version ^4.0 version while i am still using older CRUD ^3.4 with the Base ^0.9.0 which do not include the middleware `UseBackpackAuthGuardInsteadOfDefaultAuthGuard`.

copy the middleware from the latest Base version to `App\Http\Middleware` ... issue solved!

maybe should you impose version constraint ?
