### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by ludo1960** [Laravel-Backpack/PermissionManager#180]
Followed the installation instructions religiously:

Step 3:
Publish the config file & run the migrations
php artisan vendor:publish --provider="Backpack\PermissionManager\PermissionManagerServiceProvider"

Step 4:
The package assumes it's ok to use App\Models\BackpackUser to administer Users. Use a different one if you'd like by changing the user model in the config/backpack/permissionmanager.php file. Any model you're using, make sure it's using the CrudTrait and HasRoles traits:

I dont have App\Models\BackpackUser ????

Step 5:
[Optional] Add a menu item for it in resources/views/vendor/backpack/base/inc/sidebar_content.blade.php or menu.blade.php:

I dont have a resources/views/vendor/backpack/base/inc/sidebar_content.blade.php or menu.blade.php:

Step 6:

[Optional] If you want to use the @can handler inside Backpack routes, you can add a middleware to all your Backpack routes by adding this to your config/backpack/base.php file:

I dont have a config/backpack/base.php file

When I go to mysite.com?admin I get :"ReflectionException (-1)
Class App\Http\Middleware\CheckIfAdmin does not exist"

I've tried the installation 3 or 4 times, each time the same result, Any ideas guys?

**Comment by johnpuddephatt** [comment]
Try running `php artisan backpack:base:install`

You may also need to run `php artisan backpack:crud:install`

**Comment by johnpuddephatt** [comment]
@tabacitu if someone follows the installation instructions in this repo, it looks like laravel-backpack/base and laravel-backpack/crud are installed by composer but the relevant artisan install commands won't be run. Is that right?

I expect the majority of users do install base/crud first then add permission manager but some will find their way to this repo googling 'laravel permission manager' so it probably should be clearer?

**Comment by AbbyJanke** [comment]
@johnpuddwphatt looks like that is the case, didn’t run the install commands for Base and/or Crud. @tabacitu perhaps just a notice before step 1 saying this requires installing backpack base/crud first (across all packages)?

**Comment by tabacitu** [comment]
Totally, done https://github.com/Laravel-Backpack/PermissionManager/commit/473db62acca91b675e9766a6a4029cc45dec63ee , added notice to readme.

Thanks @johnpuddephatt & @AbbyJanke !
