### ISSUE TITLE
Implementing Permissions and Roles for separate user and admins table

### ISSUE THREAD

**Issue by stevecrossuk** [Laravel-Backpack/PermissionManager#187]
I'm using (and loving) Backpack 3.5, and being able to use a different table for the standard website users to the Backpack admins is great. I have a "Users" table for the front end of the website, and "admins" table for the Backpack Admin, which is setup great.

But I'm trying to make essentially two copies of the Roles and Permissions Manager, so I can implement this separately for standard website users, and separately those for Backpack.

Is it possible to run two instances of Spatie/PermissionManager?

Thanks.

**Comment by tabacitu** [comment]
Hi @stevecrossuk ,

Ugh - pretty difficult use case. So you need separate roles&permissions for users, separate roles&permissions for admins? In this case I think you'd be better off hand-coding the functionality for your Users, and keep Spatie/PermissionManager for admins.

No, you can't have two installs in one app unfortunately, and _I think_ trying to do so will probably take just as long as developing the functionality yourself...

Sorry I couldn't be of more help.
Cheers!

**Comment by stevecrossuk** [comment]
Thanks Cristian as always. 

-- 

Steve Cross
CEO



UK HQ. 01962 670 190 | Mobile. 07876 668 747| From Germany. (201)-870-48767
Email. steve@sprechen.co.uk | Web. www.sprechen.co.uk / www.geekabit.co.uk

Legal Disclaimer - This message and any attachments should only be read by those persons to whom it is addressed and be used by them for its intended purpose. Sprechen Ltd cannot accept liability for statements made which are clearly the sender's own and not made on behalf of Sprechen Ltd. Replies to this email address may be subject to interception or monitoring for operational reasons or for lawful business purposes.
