### ISSUE TITLE
adding default role on registration

### ISSUE THREAD

**Issue by mpixelz** [Laravel-Backpack/PermissionManager#19]
Hi,
how can we assign a role to a user when they register?
i have 2 different roles (admin and client) and now have 2 different registration methods (one from the front-end and second from /admin/)
how can i attach a role to users registering from the front-end?
like user signup, by default they are given role of a client.

thanks.

**Comment by mpixelz** [comment]
Thanks @tabacitu 
heres my solution.. 
Ive created a separate registration controller for front-end users (not a clean way to do it but works)
and here is my Create method attaching role to it:

```
protected function create(array $data)
    {
        $user_model_fqn = config('backpack.base.user_model_fqn');
        $user = new $user_model_fqn();

        return $user->create([
            'name'     => $data['name'],
            'email'    => $data['email'],
            'password' => bcrypt($data['password']),
        ])->assignRole('Client');;
    }
```

**Comment by tabacitu** [comment]
Hmm... actually, I think it's a pretty clean way to achieve this. I would have done it the same way.

Cheers!

**Comment by c1t1zen** [comment]
Thank you
i have did it like that and worked with me in laravel 5.4
i can assign more than role once too

`    protected function create(array $data)
    {
        return User::create([
            'name' => $data['name'],
            'email' => $data['email'],
            'password' => bcrypt($data['password']),
        ])->assignRole('user')->assignRole('user_factory');
    }`

i dont need to type :
        $user_model_fqn = config('backpack.base.user_model_fqn');
        $user = new $user_model_fqn();

**Comment by gdiasdasilva** [comment]
You can create an event and assign a listener to when a user is created (Eloquent already has [that ](https://laravel.com/docs/5.4/eloquent#events) built-in).

This way, you just have to `assignRole(...)` to the user in the listener's `handle` method.
