### ISSUE TITLE
Email field is required

### ISSUE THREAD

**Issue by acris20** [Laravel-Backpack/PermissionManager#190]
# Bug report

### What I did:

I folowed the the documentation for logging in with username https://backpackforlaravel.com/docs/3.6/base-how-to#login-with-username-instead-of-email 
I deleted the email column and removed email from fillable in the user model

### What I expected to happen:
Adding new users without the email field

### What happened:
When i try to add new users i recive the validation error: Email field is required

### What I've already tried to fix it:
Remove email field from controller
Set email nullable in UserRequest
### Backpack, Laravel, PHP, DB version:
Backpack 3.5
Laravel 5.7
Php 7.2

**Comment by tabacitu** [comment]
You're right, I failed to account for the fact that you might have a Users CRUD. In that case, the changes you mentioned are also required. I've just updated [the docs](https://backpackforlaravel.com/docs/3.6/base-how-to#login-with-username-instead-of-email) to mention that - thank you!
