### ISSUE TITLE
How to use with multiple guards?

### ISSUE THREAD

**Issue by Dontorpedo** [Laravel-Backpack/PermissionManager#195]
Hi,

i have created multiple guards like in the backpack documentation for separate logins for admin and users (backend/frontend)

so the roles and permissions stopped working and when i try to login i have the error:

Unauthorized..

how can i use the permissionmanager with multiple guards?

i didn't work that often with laravel auth.. so hope someone can help me :/

thanks in advance

**Comment by mpixelz** [comment]
have the same issue... were you able to solve this? @Dontorpedo
