### ISSUE TITLE
Password Encryption not working properly when editing

### ISSUE THREAD

**Issue by andrefigueira93** [Laravel-Backpack/PermissionManager#196]
>/vendor/backpack/permissionmanager/src/app/Http/Controllers/UserCrudController.php

### How it should be:

 ```
protected function handlePasswordInput(Request $request)
    {
        $request->request->remove('password_confirmation');
        if ($request->input('password')) {
            $request->request->set('password', Hash::make($request->input('password')));
        } else {
            $request->request->remove('password');
        }
    }
```

### How it is:

```
protected function handlePasswordInput(Request $request)
    {
        $request->request->remove('password_confirmation');
        if ($request->input('password')) {
            $request->request->set('password', bcrypt($request->input('password')));
        } else {
            $request->request->remove('password');
        }
    }
```

### Hash Fixed!
That way, no matter how is the hash mode (argon, bcrypt, argon2id), it will always hash correctly.

**Comment by tabacitu** [comment]
Hi @andrefigueira93 ,

You're right, thank you. This did not take into account if you changed your encryption algorithm. Thanks to @ziming 's PR here https://github.com/Laravel-Backpack/PermissionManager/pull/197 we've implemented your change. A ```composer update``` will fix it.

Thanks for bringing this up, and providing a solution.
Cheers!
