### ISSUE TITLE
User model does not exist (except it does)

### ISSUE THREAD

**Issue by lawsonjt** [Laravel-Backpack/PermissionManager#198]
# Bug report
User model does not exist (except it does)

### What I did:
When clicking on users from users,roles, permissions tab there is an error that says "The model does not exist."

### What I expected to happen:
I expected to see a list of users

### What happened:
Error page listed above.  It is worth noting that there is no User.php under vendor/backpack/permissionmanager/src/app/Models.  There are, however, Permission.php and Roles.php, which are the other 2 models needed for the aforementioned tab.  If this file existed, I feel this problem would not exist.

### What I've already tried to fix it:
The failure is at  vendor/backpack/permissionmanager/src/app/Http/Controllers/UserCrudController.php

specifically this line:  $this->crud->setModel(config('backpack.permissionmanager.models.user'));
If I merely replace that with $this->crud->setModel(User::class); everything works as intended. However changing vendor files would not work for anyone else that is working on this project so this is not a solution.

### Backpack, Laravel, PHP, DB version:

"backpack/permissionmanager": "^4.0"

Laravel Framework 5.6.39
PHP 7.1.17

**Comment by lawsonjt** [comment]
Apologies, this is not a bug.

I needed to add this to config/backpack/permissionmanager
```
 'models' => [
        'user'       => App\Models\User::class,
    ],
```

**Comment by Patabugen** [comment]
This wasn't required in v3, but is now required in v4.

The ChangeLog inferrs the change:

> config file for spatie/laravel-permission; models being used in CRUDs are now defined in config/backpack/permissionmanager.php;

but it'd be useful to have an "Upgrade Notice" or similar to make it more clear.
