### ISSUE TITLE
How to access current user in a CrudController

### ISSUE THREAD

**Issue by iwillhappy1314** [Laravel-Backpack/PermissionManager#20]
I can use `@role('admin')` in templates, but when a access current user by `Auth::User()` method, it returns Null, how can I access it, and use `$user->hasRole('writer')` in a CrudController ?

**Comment by tabacitu** [comment]
Hi @iwillhappy1314 ,

Starting with 5.3, Laravel no longer provides session access in constructors. And that's where the auth information is stored.

This would be a solution: https://github.com/Laravel-Backpack/CRUD/issues/95#issuecomment-246097412

Cheers!

**Comment by tabacitu** [comment]
Starting with Backpack\CRUD 3.1.24 you should be able to rename your __construct() into setup() and be able to use that.

P.S. I'll go ahead and close this issue so we don't clog the section. Feel free to open it again if you encounter problems or comment if you have follow-ups.

**Comment by iwillhappy1314** [comment]
got it, thanks!
