### ISSUE TITLE
Error 'Could not find that entry in the database' on User Edit page when route_prefix is set empty

### ISSUE THREAD

**Issue by kolexndr** [Laravel-Backpack/PermissionManager#204]
# Bug report
Error 'Could not find that entry in the database' on User Edit page when route_prefix is set to empty string.

### What I did:
I do not want 'admin' route prefix, so set it to emtpy string.

### What happened:
the line exception is happen in: 
`$userId = $this->get('id') ?? \Request::instance()->segment('3');`
located in 'UserUpdateCrudRequest' class, 'Rules' method 

### What I've already tried to fix it:
1. i've created my own UserCrudController and UserUpdateCrudRequest classes
2. Changed route to newly created UserCrudController 
3. in 'UserUpdateCrudRequest' class, 'Rules' method changed this line
`$userId = $this->get('id') ?? \Request::instance()->segment('3');`
to 
`$userId = $this->get('id') ?? \Request::instance()->segment( empty(config('backpack.base.route_prefix'))?'2':'3' );`

I hope my solution is suitable to be included in nearest fix.

### Backpack, Laravel, PHP, DB version:
Backpack 4.01, PermissionManager 5.0.0, Laravel v6.0.4

**Comment by tabacitu** [comment]
You're totally right, of course. Thank you for raising the issue, and the solution @kolexndr . I've added it to the package, so if you run a ```composer update``` and get 5.0.1 you won't have to do that trick any more.

Cheers!
