### ISSUE TITLE
Translate fields

### ISSUE THREAD

**Issue by ludioao** [Laravel-Backpack/PermissionManager#21]
Hello, how can I translate PermissionManager fields to Portuguese?

**Comment by tabacitu** [comment]
Hi @ludioao ,

You're totally right. PermissionManager isn't yet multi-language. Basically what the package needs is:
- a language file, where all translations are stored (```resources/lang/en/permissionmanager.php```) as key-value pairs;
- a PermissionManagerServiceProvider command that loads those translation ([basically this](https://github.com/Laravel-Backpack/LogManager/blob/master/src/LogManagerServiceProvider.php#L26));
- all hard-coded words or phrases in the views to be replaced with their ```trans('backpack::permissionmanager.some_key')``` counterparts;

_Only then_ can we create a new language file, (```resources/lang/pt/permissionmanager.php```), that translates those same keys.

It's definitely needed. Actually, I hadn't yet realised it's not done yet. If you can do it yourself and submit a Pull Request, it would be a wonderful contribution. If not, let's leave this issue open so we don't forget about it.

Cheers!

**Comment by ludioao** [comment]
Check my p.r

**Comment by tabacitu** [comment]
Great work ;-) Closing the issue.
