### ISSUE TITLE
Can't make @can handler work

### ISSUE THREAD

**Issue by sigalkel** [Laravel-Backpack/PermissionManager#210]
# Bug report
I'm using Laravel 6.0 with Backpack 4.0, I installed PermissionManager and it all works except for the **@can** handler 

### What I did:
I followed the instructions and added a middleware to my Backpack routes by adding the following to the config/backpack/base.php :

```
 // The classes for the middleware to check if the visitor is an admin
    // Can be a single class or an array of clases
'middleware_class' => [
        App\Http\Middleware\CheckIfAdmin::class,
        \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
        \Backpack\CRUD\app\Http\Middleware\UseBackpackAuthGuardInsteadOfDefaultAuthGuard::class,
    ]
```
Please can you help?

**Comment by ziming** [comment]
I think that's because can check with the default auth guard but backpack uses it's own seperate auth guard.

So do something like `@if(backpack_user()->can('viewAny', App\Models\User::class)` instead.

**Comment by sigalkel** [comment]
Thank you, Ziming.

**Comment by pxpm** [comment]
Hello @sigalkel .

Thanks for your help @ziming :+1: 

Another way to do it is writting your custom blade directective, laravel documentation provide examples :)

Best,
Pedro
