### ISSUE TITLE
Role and permission name required

### ISSUE THREAD

**Issue by adal6a** [Laravel-Backpack/PermissionManager#211]
# Bug report
Role and permission name (required) is not marked as required

### What I did:
Install package and use config by default

### What I expected to happen:
Role and permission validation as required to create/update

### What happened:
Role and permission name is not marked as required to create/update

### What I've already tried to fix it:
Overwriting functionality and:

I added RoleRequest and PermissionRequest to apply rules validation and is working

### Backpack, Laravel, PHP, DB version:
Bacpack: 4.0
Laravel: 6.2
PHP: 7.2
BD: SQL Server

**Comment by tabacitu** [comment]
You're totally right. Thank you @adal6a . It looks like when I've refactored for Backpack v4, I've forgotten to put in the validation. Thankfully the DB validation was in place, so nobody's db has been corrupted. But asterisks and proper validation messages should be in place, I agree. I've just pushed an update adding proper validation and asterisks. You can get it using ```composer update```, it will pull PermissionManager 5.0.3 or higher.

Cheers!
