### ISSUE TITLE
After fresh install can't access authentification/user  

### ISSUE THREAD

**Issue by eletec** [Laravel-Backpack/PermissionManager#212]
I just install Laravel/BackPack 4 on wamp (php7.2.18/mysql 5.7.26)

After PermissionManager install I get this error trying to acess user authentification/user section 

Local.ERROR: Please use CrudTrait on the model. {"exception":"[object] (Exception(code: 500): Please use CrudTrait on the model. at C:\\wamp64\\www\\backpack\\vendor\\backpack\\crud\\src\\app\\Library\\CrudPanel\\CrudPanel.php:84)

I've installed step by step with the instructions from backpack page

All works fine except user section. I notice User table is not updated after install and does'n have a roles fields. Seem's not normal...

maybe something is missing in the install instructions ?

 more : Infortunatly I could not install the usermanager module due to dependance problem

- Installation request for eduardoarandah/usermanager ^1.0 -> satisfiable by eduardoarandah/usermanager[1.0.0, 1.0.x-dev].
- Can only install one of: backpack/crud[3.6.x-dev, 4.0.22].
- Can only install one of: backpack/crud[4.0.22, 3.6.x-dev].
- Can only install one of: backpack/crud[3.6.x-dev, 4.0.22].
- Conclusion: install backpack/crud 3.6.x-dev
- Installation request for backpack/crud (locked at 4.0.22, required as 4.0.*) -> satisfiable by backpack/crud[4.0.22].

Installation failed, reverting ./composer.json to its original content.

Are those packages ready for Laravel 6 /  BackPack 4 ?

**Comment by pxpm** [comment]
Hello @eletec 

I think you are trying to install some other package `Installation request for eduardoarandah/usermanager ^1.0 ` 

You should be installing `backpack/permissionmanager`

Where did you get the instructions to do a clean install ? from [official backpack docs](https://backpackforlaravel.com/docs/4.0/installation) ?

We also use github to deal with issues/features so i am going to close this. 

If you still think this is a bug (bad documentation is likely a bug :+1: ) Please re-open, or ask for help in the channels provided in __Support Bot__ message. :)

Best,
Pedro
