### ISSUE TITLE
[4.0][BUG] authentication_column config does not apply to user crud.

### ISSUE THREAD

**Issue by daimalkogaz** [Laravel-Backpack/PermissionManager#213]
# Bug report

### What I did: 
On a fresh project installation I installed the permission manager following all the steps in the docs. However after adding the elements in the admin side-bar whenever I try to Add a new user or Edit a user by default it uses email fields instead of username.

This happens after I have already replaced the 
    'authentication_column'      => 'email',
    'authentication_column_name' => 'Email',

with 'username' and 'Username' in the config/backpack/base.php

### What I expected to happen: 
The email fields get switched with username like they did in the login and register pages.

### Backpack, Laravel, PHP, DB version:

        "php": "^7.2",
        "laravel/framework": "^6.2",
        "backpack/crud": "4.0.*",
        "backpack/permissionmanager": "^5.0",

**Comment by pxpm** [comment]
Hello @daimalkogaz did you clear your config with: `php artisan config:clear` ?? 

Maybe you still the old config cached :+1: 

Best,
Pedro

**Comment by daimalkogaz** [comment]
> Hello @daimalkogaz did you clear your config with: `php artisan config:clear` ??
> 
> Maybe you still the old config cached 👍
> 
> Best,
> Pedro

No, it's still the same. The login/register page has properly changed to using a username, but the new Sidebar menus added after the permission manager are using the email values.

**Comment by pxpm** [comment]
Ok, i got it! It's indeed something i will discuss with @tabacitu , changing the default user implementation to: 

```
           [
                'name'  => config('backpack::base.authentication_column'),
                'label' => trans('backpack::permissionmanager.email'),
                'type'  =>config('backpack::base.authentication_column_type'),
            ],
```

For now you need to override the `UserCrudController`. Create your own `MyUserCrudController` that extends the original. Modify the email field to the field you want. 

Best,
Pedro

**Comment by tabacitu** [comment]
Hmmm indeed, I think we should support username too. I wouldn’t add a new config variable for the field type though, i’d just assume that if the auth column is not email then it’s a text. 

We should also change the validation - unique is still required in this case but not “email”.

Will do. Thanks @daimalkogaz!

**Comment by AbbyJanke** [comment]
I agree adding a `type` setting seems a bit unfriendly. I think for now it is an easy fix to just make it 'string' cause an email is still a string. otherwise a thought is do something like:

```php
$type = 'string';
if(strpos(config('backpack::base.authentication_column'), 'email') !== false){
   $type = 'email';
}
```

**Comment by AbbyJanke** [comment]
@daimalkogaz not sure if you are still looking for this, I submitted a PR for this.

**Comment by tabacitu** [comment]
Thank you so much @AbbyJanke . Let's close this, and move the conversation over to your PR #236 in order to get this fixed once and for all. Thanks everyone!
