### ISSUE TITLE
Roles not working in blade

### ISSUE THREAD

**Issue by FreddyCrugger** [Laravel-Backpack/PermissionManager#214]
# Bug report
Roles not working in blade
### What I did:
Added Laravel-Backpack/PermissionManager to Backpack 4 and Laravel 6(all latest)
When adding this in blade:
```
@role('admin')
<li class="nav-item nav-dropdown">
    <a class="nav-link nav-dropdown-toggle" href="#"><i class="nav-icon fa fa-group"></i> Authentication</a>
    <ul class="nav-dropdown-items">
        <li class="nav-item"><a class="nav-link" href="{{ backpack_url('user') }}"><i class="nav-icon fa fa-user"></i> <span>Users</span></a></li>
        <li class="nav-item"><a class="nav-link" href="{{ backpack_url('role') }}"><i class="nav-icon fa fa-group"></i> <span>Roles</span></a></li>
        <li class="nav-item"><a class="nav-link" href="{{ backpack_url('permission') }}"><i class="nav-icon fa fa-key"></i> <span>Permissions</span></a></li>
    </ul>
</li>
@else
    I am not a writer...
@endrole
```
I always get the output "I am not a writer..."
### What I expected to happen:
I expected to see the menus as I am set as admin role.

### What I've already tried to fix it:
I checked many times the roles:
![images](https://user-images.githubusercontent.com/6231274/71283870-b5f8c200-2361-11ea-9248-9db4403fca88.png)

I emptied the cache:
```
php artisan cache:clear
php artisan view:clear
php artisan config:clear
php artisan config:cache
php artisan route:cache
```

### Backpack, Laravel, PHP, DB version:
```
    "require": {
        "php": "^7.2",
        "backpack/crud": "4.0.*",
        "backpack/permissionmanager": "^5.0",
        "backpack/settings": "^3.0",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "^6.2",
        "laravel/tinker": "^2.0",
        "oscarafdev/migrations-generator": "2.0.13",
        "spatie/laravel-permission": "^3.3"
    },
    "require-dev": {
        "backpack/generators": "^2.0",
        "facade/ignition": "^1.4",
        "fzaninotto/faker": "^1.4",
        "laracasts/generators": "^1.1",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^3.0",
        "phpunit/phpunit": "^8.0"
    },
```

User model:
```
<?php

namespace App;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Backpack\CRUD\app\Models\Traits\CrudTrait;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable;
    use CrudTrait;
    use HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}
```

Whatever I try, I cannot get the role to be picked up.

Any idea why please?

Thank you.

**Comment by pxpm** [comment]
My guess is that you haves misconfigured guards.

Check it out, I am not aware of any issue with permissions like that. Also
check for backpack_user()->hasRole('writer')

Best,
Pedro

A sexta, 20/12/2019, 19:01, welcome[bot] <notifications@github.com>
escreveu:

**Comment by FreddyCrugger** [comment]
Thank you so much
It worked!!

**Comment by royrakesh** [comment]
Hi Same issue 
PHP code  worked 


![image](https://user-images.githubusercontent.com/15174104/75115953-a495a400-5689-11ea-98a2-c701b513d877.png)

but blade syntax not working

![image](https://user-images.githubusercontent.com/15174104/75115962-c4c56300-5689-11ea-8fb1-1af6d830ca57.png)

**Comment by tabacitu** [comment]
Indeed @royrakesh - the ```@role('admin')``` syntax does not take into account to use the Backpack guard.

You can either:
A) use ```backpack_user()->hasRole('admin')```;
or
B) change the guard that Backpack uses to the default guard; in ```config/backpack/base.php``` change ```'guard' => null,``` - this should let you use the ```@role('admin')``` syntax.

Cheers!
