### ISSUE TITLE
Filter users by role.

### ISSUE THREAD

**Issue by ishan911** [Laravel-Backpack/PermissionManager#215]
Is there anyway to filter the users by role?

**Comment by tabacitu** [comment]
Hi @ishan911 ,

You're right. There's no reason the Users CRUD wouldn't have a filter to for Roles. I've just pushed an update where I've added that filter. I've also added a filter for Extra Permissions. You should be able to do a ```composer update``` to get 3.3.1, that has these filters.

In any case, for posterity, here's how to add a Roles filter, in your ```setupListOperation()```:

```php
        $this->crud->addFilter([
          'name' => 'role',
          'type' => 'dropdown',
          'label'=> 'Role'
        ], 
        config('permission.models.role')::all()->pluck('name', 'id')->toArray(), 
        function($value) { // if the filter is active
          $this->crud->addClause('whereHas', 'roles', function ($query) use ($value) {
            $query->where('role_id', '=', $value);
          });
        });
```

Cheers!

**Comment by ishan911** [comment]
> Hi @ishan911 ,
> 
> You're right. There's no reason the Users CRUD wouldn't have a filter to for Roles. I've just pushed an update where I've added that filter. I've also added a filter for Extra Permissions. You should be able to do a `composer update` to get 3.3.1, that has these filters.
> 
> In any case, for posterity, here's how to add a Roles filter, in your `setupListOperation()`:
> 
> ```
>         $this->crud->addFilter([
>           'name' => 'role',
>           'type' => 'dropdown',
>           'label'=> 'Role'
>         ], 
>         config('permission.models.role')::all()->pluck('name', 'id')->toArray(), 
>         function($value) { // if the filter is active
>           $this->crud->addClause('whereHas', 'roles', function ($query) use ($value) {
>             $query->where('role_id', '=', $value);
>           });
>         });
> ```
> 
> Cheers!

Thanks for the update.
