### ISSUE TITLE
Cannot get the permissions to work in v4

### ISSUE THREAD

**Issue by FreddyCrugger** [Laravel-Backpack/PermissionManager#217]
Laravel 6.2
BackPack v4

#Trying to use Laravel-BackPack Permissions in blade. I am currently set as an "Admin"

When trying to use the permissions in Backpack, nothing happens. Both the links are hidden:

![1](https://user-images.githubusercontent.com/6231274/72016879-e5199980-3264-11ea-9f39-2194a43b97ee.png)
![2](https://user-images.githubusercontent.com/6231274/72016880-e5199980-3264-11ea-80b1-321a6185e9e7.png)

```
<li> 
<ul>
@if(backpack_user()->can('read admin link'))
<li class="nav-item"><a class="nav-link" href=""><i class="nav-icon fa fa-user"></i> <span>Can only 
be seen by admins</span></a></li>
@endif
@if(backpack_user()->can('read user link'))
<li class="nav-item"><a class="nav-link" href=""><i class="nav-icon fa fa-user"></i> <span>Can only 
be seen by users</span></a></li>
@endif
</ul>
</li>
```

Here is my base.php
```
'middleware_class' => [
    App\Http\Middleware\CheckIfAdmin::class,
    \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
    // \Backpack\CRUD\app\Http\Middleware\UseBackpackAuthGuardInsteadOfDefaultAuthGuard::class,
],
```

Any idea why this does not work, I followed the doc here:
https://github.com/Laravel-Backpack/PermissionManager

Thank you.

**Comment by francoisauclair911** [comment]
I think your issue may have something to do with the fact that the default guard when you create a role is `web` (same for permissions) and backpack default guard is `backpack` 

Try to set the guard to backpack for your role and permissions and try again


[related ](https://github.com/Laravel-Backpack/PermissionManager/issues/193#issuecomment-562969199)

**Comment by FreddyCrugger** [comment]
Thank you so much!
In fact, when I added this class it did not work...I scratched me head for a good hour to find out that in the database, you have to delete the current roles because if you don't they still keep the "web" guard from the previous settings :-) Cool! One thing sorted!.....
