### ISSUE TITLE
Customise Controllers and Requests

### ISSUE THREAD

**Issue by b8ne** [Laravel-Backpack/PermissionManager#22]
I posted something similar in Base yesterday, now im looking for the same thing with permissions,
I want to be able to customise the crudcontrollers so that I can alter the views, however currently all logic lies in /vendor so is not version control safe.
I was thinking to store them in App\Http\Controllers\Permissions, however Im not sure how to re-route?
Cheers

**Comment by b8ne** [comment]
Ended up just forking and changing namespaces, routing etc... Assuming you wont want to pull this but im happy to post anything if anyone else is looking for a similar solution

**Comment by tabacitu** [comment]
Hmm... I think a better solution would be to create your own controller, that extends the one in vendor/backpack/permissionmanager. That way, you can still receive updates, but can overwrite whatever you need.

In the future we should provide an artisan command to generate those for you, so it would be easier. You're right. Cheers!
