### ISSUE TITLE
[4.0] removeRole function cannot accept collection

### ISSUE THREAD

**Issue by shineirvin** [Laravel-Backpack/PermissionManager#222]
# Bug report

### What I did:
I'm trying to use the removeRole function with **a collection** as parameters.
```
$current_roles = backpack_user()->roles; // collections
if (count($current_roles)) {
    backpack_user()->removeRole($current_roles);
}
```

### What I expected to happen:
Successfully remove user roles as the docs says
```
The assignRole, hasRole, hasAnyRole, hasAllRoles 
and removeRole-functions can accept a string, a Role-object
or an \Illuminate\Support\Collection-object.
```

### What happened:
I got this error message
```
Return value of App\Models\BackpackUser::getStoredRole() must implement interface 
Spatie\Permission\Contracts\Role, instance of Illuminate\Database\Eloquent\Collection 
returned
```

### Backpack, Laravel, PHP, DB version:
Backpack/crud: 4.0
Laravel: 6.2
PHP: 7.2
DB: MySQL 5.6

**Comment by tabacitu** [comment]
@schnettker , it doesn't look like it could be a Backpack problem, to me. 

```assignRole, hasRole, hasAnyRole, hasAllRoles and removeRoles``` are all methods provided by spatie/permission-manager - so I think there might be a problem there.

Have you figured this out yet?
