### ISSUE TITLE
Role and Permission Routes not accessible or do not exist

### ISSUE THREAD

**Issue by selected-pixel-jameson** [Laravel-Backpack/PermissionManager#231]
# Bug report

### What I did:
Followed the instructions in the readme file as close as possible.

### What I expected to happen:
A UI to be shown when navigation to /admin/role and/or /admin/permission

### What happened:
I receive a 404 error page.

### What I've already tried to fix it:
Everything.. 

### Backpack, Laravel, PHP, DB version:
Backpack 4.0
Laravel 6.18
DB MySQL 5.7

See SO post

https://stackoverflow.com/questions/61371729/unable-to-access-route-for-role-and-permissions-using-laravel-backpack-permissio

**Comment by pxpm** [comment]
Hello @selected-pixel-jameson 

Can you see the routes in `php artisan route:list` ?

**Comment by selected-pixel-jameson** [comment]
No I do not see them printed out in that command. 

I manually tried to add them to the custom.php routes but when I do that it just throws an error, styled via Backpack, stating that the controllers I'm specifying don't exist.

**Comment by pxpm** [comment]
Very strange. 

I'v just checked in demo and it's working. 

Could you try clearing the cache ? `php artisan cache:clear`

**Comment by selected-pixel-jameson** [comment]
You're telling me. This was working locally for us as we used to be running laravel 5.8. Then we updated to 6 and ran composer install and now it is not working.

**Comment by pxpm** [comment]
Hum .. you have the vendor/backpack/permissionmanager folder? 

I think you should run `composer update` instead of install. 

Have you tried it ?

**Comment by selected-pixel-jameson** [comment]
So the routes/backpack/permissionmanager.php file had nothing in it.

I added the default from the repo and it seems to be working now. 

```
Route::group([
    'namespace'  => 'Backpack\PermissionManager\app\Http\Controllers',
    'prefix'     => config('backpack.base.route_prefix', 'admin'),
    'middleware' => ['web', backpack_middleware()],
], function () {
    Route::crud('permission', 'PermissionCrudController');
    Route::crud('role', 'RoleCrudController');
    Route::crud('user', 'UserCrudController');
});
```

**Comment by AbbyJanke** [comment]
Strange that happened. Just tried to replicate it on 3 new fresh installs and nothing. Could be composer or something just didn't get the contents for some reason. Going to close this since its solved.
