### ISSUE TITLE
Cannot access protected property Backpack\CRUD\app\Library\CrudPanel\CrudPanel::$request

### ISSUE THREAD

**Issue by Ceepster14** [Laravel-Backpack/PermissionManager#233]
# Bug report

### Further info:

I'm using the standard App/User model which has the Backpack\CRUD\app\Models\Traits\CrudTrait and the Spatie\Permission\Traits\HasRoles trait applied to it.

In config/backpack/base.php the guard property is set to 'backpack' and \Backpack\CRUD\app\Http\Middleware\UseBackpackAuthGuardInsteadOfDefaultAuthGuard::class is set in the middleware_class array.

In config\backpack\permissionmanager.php the user model is set to App\User::class

**Comment by tabacitu** [comment]
Indeed - it's something that's changed between Backpack 4.0 and 4.1. This PR fixes it https://github.com/Laravel-Backpack/PermissionManager/pull/228

To use that branch now, while Backpack 4.1 is still in beta, please either use:
```
        "backpack/crud": "4.1.x-dev as 4.1.0",
```
or
```
        "backpack/permissionmanager": "^6.0|4.1.x-dev as 6.0.0",
```

Cheers!
