### ISSUE TITLE
manage permissions automatically for essential CRUD operations

### ISSUE THREAD

**Issue by webdesign7** [Laravel-Backpack/PermissionManager#234]
Is there an easy way of  managing access to essential crud operations , currently I am doing like this in  `setup()` function  .. but I wonder if there is a way to do this simpler , without repeating the same for each controller .. any ideas ? 
       
    `if ( !backpack_user()->hasPermissionTo('delete') )
        {
            $this->crud->denyAccess('delete');
        }

        if ( !backpack_user()->hasPermissionTo('create') )
        {
            $this->crud->denyAccess('create');
        }

        if ( !backpack_user()->hasPermissionTo('update') )
        {
            $this->crud->denyAccess('update');
        }`

**Comment by tabacitu** [comment]
@webdesign7 you should be able to do this inside a PHP trait, then just re-use that trait on all Controllers where you want this.
