### ISSUE TITLE
Blocking permission Manager Routes

### ISSUE THREAD

**Issue by riddy92** [Laravel-Backpack/PermissionManager#239]
### What I did:
 
 I wanted to restrict the routes for permission manager to 'role:admin'.

I created permissionmanager.php in routes/backpack/

```
Route::group([
	'prefix' => config('backpack.base.route_prefix', 'admin'), 
	'middleware' => ['role:admin'], 
	'namespace' => 'Backpack\PermissionManager\app\Http\Controllers'
], function () {
  	Route::crud('permission', 'PermissionCrudController');
    Route::crud('role', 'RoleCrudController');
    Route::crud('user', 'UserCrudController');
  
});
```

### What I expected to happen:

I currently have 2 roles, admin and editor. I expected Editor to not have access to the routes

### What happened:

Both the admin and editor are denied access with an Error 403 forbidden, User is not logged in

###Addition:

I am able to use the blade directive without any issues in sidebar_content.blade.php

```
<?php if(backpack_user()->hasRole('admin')): ?>
 
	<li class="nav-item nav-dropdown">
		<a class="nav-link nav-dropdown-toggle" href="#"><i class="nav-icon fa fa-group"></i> Authentication</a>
		<ul class="nav-dropdown-items">
		  <li class="nav-item"><a class="nav-link" href="{{ backpack_url('user') }}"><i class="nav-icon fa fa-user"></i> <span>Users</span></a></li>
		  <li class="nav-item"><a class="nav-link" href="{{ backpack_url('role') }}"><i class="nav-icon fa fa-group"></i> <span>Roles</span></a></li>
		  <li class="nav-item"><a class="nav-link" href="{{ backpack_url('permission') }}"><i class="nav-icon fa fa-key"></i> <span>Permissions</span></a></li>
		</ul>
	</li>

<?php endif; ?>
```

### PHP VERSION:
PHP 7.3.7 (cli) (built: Jul 16 2019 16:30:30) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.7, Copyright (c) 1998-2018 Zend Technologies

### LARAVEL VERSION:
v7.11.0@f4563bd2e0875c59a1f7967abdbe5cef7f240117

### BACKPACK VERSION:
4.1.4@4303aa07ec0c597abfcfe83896558ca6e98f0d6a

Server version: 5.7.26 - MySQL Community Server (GPL)

**Comment by AbbyJanke** [comment]
So in the `config/backpack/permissionmanager.php` you should have settings for `edit`, `update` and `delete`. Currently there is nothing restricting "reading" if that's something that is wanted perhaps that can be explored. But if you manually enter the URL right now you will get it. if its not in the navbar, unlikely somebody will be able to guess it as it does not even appear in the source code.

**Comment by riddy92** [comment]
I have managed to reach my expectations by

1) config/backpack/base.php
   `  'guard' => 'web',`

2) config/backpack/base.php ... commenting the 3rd link
    ```
  'middleware_class' => [
        App\Http\Middleware\CheckIfAdmin::class,
        \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
        // \Backpack\CRUD\app\Http\Middleware\UseBackpackAuthGuardInsteadOfDefaultAuthGuard::class,
    ],
```
3)creating routes/backpack/permissionmanager.php
       ```
Route::group([
	'prefix' => config('backpack.base.route_prefix', 'admin'), 
	'middleware' => ['web', 'role:admin'], 
	'namespace' => 'Backpack\PermissionManager\app\Http\Controllers'
], function () {
  	Route::crud('permission', 'PermissionCrudController');
    Route::crud('role', 'RoleCrudController');
    Route::crud('user', 'UserCrudController');
    // other routes
});
```

**Comment by riddy92** [comment]
I have managed to reach my expectations by

config/backpack/base.php
`'guard' => 'web',`

config/backpack/base.php ... commenting the 3rd link
```

'middleware_class' => [
App\Http\Middleware\CheckIfAdmin::class,
\Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
// \Backpack\CRUD\app\Http\Middleware\UseBackpackAuthGuardInsteadOfDefaultAuthGuard::class,
],

```
3)creating routes/backpack/permissionmanager.php
      ```
 
Route::group([
	'prefix' => config('backpack.base.route_prefix', 'admin'), 
	'middleware' => ['web', 'role:admin'], 
	'namespace' => 'Backpack\PermissionManager\app\Http\Controllers'
], function () {
  	Route::crud('permission', 'PermissionCrudController');
    Route::crud('role', 'RoleCrudController');
    Route::crud('user', 'UserCrudController');
    // other routes
});
```

**Comment by riddy92** [comment]
I have managed to reach my expectations by

config/backpack/base.php
'guard' => 'web',

config/backpack/base.php ... commenting the 3rd link


'middleware_class' => [
App\Http\Middleware\CheckIfAdmin::class,
\Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
// \Backpack\CRUD\app\Http\Middleware\UseBackpackAuthGuardInsteadOfDefaultAuthGuard::class,
],

3)creating routes/backpack/permissionmanager.php

Route::group([
'prefix' => config('backpack.base.route_prefix', 'admin'),
'middleware' => ['web', 'role:admin'],
'namespace' => 'Backpack\PermissionManager\app\Http\Controllers'
], function () {
Route::crud('permission', 'PermissionCrudController');
Route::crud('role', 'RoleCrudController');
Route::crud('user', 'UserCrudController');
// other routes
});

**Comment by riddy92** [comment]
I  have managed to reach my expectations by

1. config/backpack/base.php
 `'guard' => 'web',`

2. config/backpack/base.php 

```
'middleware_class' => [ 
App\Http\Middleware\CheckIfAdmin::class, \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class, // \Backpack\CRUD\app\Http\Middleware\UseBackpackAuthGuardInsteadOfDefaultAuthGuard::class, 
],
```


3) creating routes/backpack/permissionmanager.php

`Route::group([ 'prefix' => config('backpack.base.route_prefix', 'admin'), 'middleware' => ['web', 'role:admin'], 'namespace' => 'Backpack\PermissionManager\app\Http\Controllers' ], function () { Route::crud('permission', 'PermissionCrudController'); Route::crud('role', 'RoleCrudController'); Route::crud('user', 'UserCrudController'); // other routes });`
