### ISSUE TITLE
BackPack Laravel Login issues with multi-tenants

### ISSUE THREAD

**Issue by dmsherazi** [Laravel-Backpack/PermissionManager#245]
I am using **laravel 7** , with backpack for laravel and **stancl/tenancy** package to implement multi db multi tenant application. For permissions and roles I am using the **Laravel-Backpack/PermissionManager**

So far I am able to create tenants and login according to the users in the tenant. For the central DB logins and access to different pages work fine. On the tenant , I can login and the system loads the dashboard. But when I try to open any other page It redirects back to dashboard. In the middle ware I see that the logic is_guest() is true and that causes the redirect to dashboard.

Please guide me how to solve this!

### Backpack, Laravel, PHP, DB version:
PHP Ver 7.2 , MYSQL . LARAVEL 7

**Comment by tabacitu** [comment]
Hi @dmsherazi ,

I'm afraid I'm not familiar with how stancl/tenancy works with Backpack, and what's needed to make them work well together. 

But if you've narrowed down the problem to be inside the `CheckIfAdmin` middleware, that should be super-simple to solve. The `CheckIfAdmin.php` file is in your project, in _userland_, you can modify it as you please, including removing the `guest()` usage for something that better suits your needs.

Hope it helps.
Cheers!
