### ISSUE TITLE
I cannot assign role and permission with backpack demo project

### ISSUE THREAD

**Issue by thychanarith** [Laravel-Backpack/PermissionManager#253]
#42 # What happened:
When I create new user and assign role and permission to it it not working.

**Comment by DoDSoftware** [comment]
It's hard to say without seeing your code, but I suspect that the issue _might_ be related to cached permissions. After you assign a permission/role to a user, run `Cache::forget(config('permission.cache.key'));` then test if the permission is applied.

If this doesnt fix the issue, could you please create a question on stackoverflow.com including the your code, then tag it with backpack-for-laravel and post the link here? Im sure with that information we can help get you sorted :)

**Comment by tabacitu** [comment]
Totally agree with what @DoDSoftware said. I've just tried it myself and it seemed to work fine for me. In case this keep happening and you think it's a bug please let us know more about this @thychanarith and we'll reopen.
