### ISSUE TITLE
Wrong $routeSegmentWithId in vendor/backpack/permissionmanager/src/app/Http/Requests/UserUpdateCrudRequest.php

### ISSUE THREAD

**Issue by EvgeniySyo** [Laravel-Backpack/PermissionManager#258]
# Bug report

Error, when edit user

### What I did:

Edit user

### What I expected to happen:

View editing form

### What happened:

Got an error: Could not find that entry in the database.

### What I've already tried to fix it:

Change $routeSegmentWithId = empty(config('backpack.base.route_prefix')) ? '2' : '3';
to $routeSegmentWithId = empty(config('backpack.base.route_prefix')) ? '2' : '6';
Because my route prefix in config is  '/api/web/travel/admin', and I get 'travel', but properly I must get user ID

![permission_manager](https://user-images.githubusercontent.com/42005675/99364620-3c49bb00-28c7-11eb-8928-7f93f652749c.png)

### Backpack, Laravel, PHP, DB version:

Backpack 4.1

Laravel 7.x
PHP 7.3
DB Maria DB 10.x

**Comment by promatik** [comment]
@EvgeniySyo thank you for your report.
I just pushed a PR to solve this issue https://github.com/Laravel-Backpack/PermissionManager/pull/259, let's move the conversation there and I'll close this issue for now, let's hope for a quick merge into production.

If you are able to, please test the code in https://github.com/Laravel-Backpack/PermissionManager/pull/259, and tell us if it solves your problem.
