### ISSUE TITLE
Configuration for middleware protection of admin route

### ISSUE THREAD

**Issue by RokSiEu** [Laravel-Backpack/PermissionManager#260]
# Documentation on middleware usage with combination of backpack, backpack/PermissionManager and spatie/laravel-permissions 

### What I did:

1. created user
2. checked that user does NOT have any roles / permissions assigned
3. navigated to /admin 

### What I expected to happen:
user without role (super-admin) should not be able to access /admin/ part of site

### What happened:
user had access

### What I've already tried to fix it:
Modified:
config/backpack/base.php
```
'user_model_fqn' => App\Models\User::class,
    'middleware_class' => [
        //App\Http\Middleware\CheckIfAdmin::class,
        \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
        \Backpack\CRUD\app\Http\Middleware\UseBackpackAuthGuardInsteadOfDefaultAuthGuard::class,
    ],
'guard' => 'web',
```

added ['role:super-admin'] in the middleware of routes/backpack/custom.php
```
Route::group([
    'prefix'     => config('backpack.base.route_prefix', 'admin'),
    'middleware' => array_merge(
        (array) config('backpack.base.web_middleware', 'web'),
        (array) config('backpack.base.middleware_key', 'admin'),
        ['role:super-admin']
    ),
    'namespace'  => 'App\Http\Controllers\Admin',
], function () { // custom admin routes
}); // this should be the absolute last line of this file
```

**Comment by pxpm** [comment]
Hello @RokSiEu, thank you very much for your report. 

If I understand correctly your issue, commenting `App\Http\Middleware\CheckIfAdmin` is the oposite of the solution. 

That middleware is provided so you can configure it at your will and decide who can/cannot access backpack routes. 

https://backpackforlaravel.com/docs/4.1/base-about#routes

If you check that file: https://github.com/Laravel-Backpack/CRUD/blob/master/src/app/Http/Middleware/CheckIfAdmin.php

it has the instructions to do what you are looking for. 

I don't think there is a bug here so I will be closing this issue for now, if I am wrong please re-open, I also make mistakes :)

Will let the bot close this one so you get the Links for our mediums where you can find lots of information and people who might be able to help you in any questions you have about Backpack.

Wish you the best,
Pedro
