### ISSUE TITLE
Unable to open users panel

### ISSUE THREAD

**Issue by Deca** [Laravel-Backpack/PermissionManager#265]
# Bug report

### What I did:
followed PermissionManager and spatie/laravel-permission, installation process 

### What I expected to happen:
access to the authentication/users panel
### What happened:
Getting expection "The model does not exist."

### What I've already tried to fix it:
tried to create a user model in  vendor\backpack\permissionmanager\src\app\Models but for what I've undestood it should use by default App\Models\BackpackUser

### Backpack, Laravel, PHP, DB version:
Backpack 4.1, laravel 8.1, php 7.4

**Comment by pxpm** [comment]
Hello @Deca .

You should not create files inside vendor folder. If you followed the setup tutorial you should have `permission.php` in your config folder. 

There you can configure the user model you use in your application (In the latest Backpack versions, BackpackUser have been deprecated) so you should update your config to match your user model. (In Laravel 8, probably `App\Models\User`. If you cache your config don't forget to clear the cache `php artisan config:clear`

Don't forget to add the traits to that model (as we describe in setup documentation). 

I don't think there is a bug here, so I am going to close this. 

If you have any general questions like this, I suggest you to post to some other mediums, as we use github only for bugs/features. 

https://gitter.im/BackpackForLaravel/Lobby
https://www.reddit.com/r/BackpackForLaravel/
https://stackoverflow.com/questions/tagged/backpack-for-laravel

If I am wrong here, and I am a lot of times, please re-open.

Best,
Pedro
