### ISSUE TITLE
Support for spatie/laravel-permission v4

### ISSUE THREAD

**Issue by abejenaru** [Laravel-Backpack/PermissionManager#269]
# Bug report

### What I did:

composer require backpack/permissionmanager

### What happened:

backpack/permissionmanager[6.0.0, ..., 6.0.4] require spatie/laravel-permission ^3.0 -> found spatie/laravel-permission[3.0, ..., v3.x-dev] but it conflicts with your root composer.json require (^4.0)

**Comment by promatik** [comment]
Hi @abejenaru!
I just pushed a PR to fix this #271. It seems to me this version has no major breaking changes so it may get merged soon.

Thank you for opening the issue 🙌
Let's move the conversation to #271.
