### ISSUE TITLE
I want to use Roles, but not Permissions. How to disable, or at least hide Permission's content.

### ISSUE THREAD

**Issue by franciscocorrales** [Laravel-Backpack/PermissionManager#27]
Hi,

I've been just using Roles as the whole roles-permission manager. Because simply sometimes a website is not that complex. The whole thing is working perfectly. So, I think that this partial use of this package is acceptable.

But now, there's seem to be a little problem, I tried to check the code (checklist_dependency, ...) , but it is above my level.
<img width="481" alt="screen shot 2016-10-18 at 16 39 01" src="https://cloud.githubusercontent.com/assets/4010693/19499052/752df980-9551-11e6-89d8-212823a1920d.png">

**I can't  remove (or simply just hide that last  Permission label).** on the edit/create User view.

**Comment by tabacitu** [comment]
Hi @franciscocorrales ,

I guess the only way to achieve this right now would be to overwrite the UserCrudController. You can do that by 
- creating a new controller in your project, that extends the one in Backpack;
- adding the same route to your web.php routes file, but that points to that new controller;

Then you can make any modifications you want in the new controller. For example, you could remove the roles & permissions field and add a simple select2 field to choose the appropriate role;

Would that work for you?

**Comment by franciscocorrales** [comment]
> @tabacitu wrote: ...overwrite the UserCrudController...

So far so good. I've done that already. I'll try what you suggested about using the _select2_ field.
I'll come back soon.

Thanks.

**Comment by franciscocorrales** [comment]
I edited my comment with more information.

**Comment by tabacitu** [comment]
Hi @franciscocorrales ,

I meant select_multiple or select2_multiple, yes. These are for n-n relationships, select is only for 1-n.

In order for the save to actually happen on the select2_multiple you need to specify to update the pivot table. Check out the [select2_multiple documentation](https://laravel-backpack.readme.io/docs/crud-fields#select2_multiple-n-n-relationship):

```php
[ 
   'label' => 'Roles',
   'type' => 'select2',
   'name' => 'roles',
   'entity' => 'roles',
   'attribute' => 'name',
   'model' => "Backpack\PermissionManager\app\Models\Role",
    'pivot' => true, // <-------------------------------------- don't forget this line
],
```

Cheers!

**Comment by tabacitu** [comment]
P.S. I'll go ahead and close this issue so we don't clog the section - I'm sure that will do the trick. Feel free to open it again if you encounter problems or comment if you have follow-ups.

**Comment by franciscocorrales** [comment]
Ok, _select_multiple_ or _select2_multiple_ do work !, Thanks.

------------------------------------

Note (maybe a bug ?):
In the roles selection, there's an **-** option, which can be selected. But if the user tries to saved that, that will cause an error.
<img width="272" alt="screen shot 2016-10-21 at 08 46 45" src="https://cloud.githubusercontent.com/assets/4010693/19602628/28291c52-976b-11e6-9848-0fba7ee92061.png">
<img width="156" alt="screen shot 2016-10-21 at 08 46 55" src="https://cloud.githubusercontent.com/assets/4010693/19602629/2b76cab2-976b-11e6-82f9-e4a30510ff39.png">

`SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (mydatabase.role_users, CONSTRAINT role_users_role_id_foreign FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE) (SQL: insert into role_users (role_id, user_id) values (, 12))`

**Comment by franciscocorrales** [comment]
Ok, this is my solution if you want to:

- Only use Roles
- User can only have one Role

Set your field:
```
[ 
	'label' => "Roles",
	'type' => 'selectRoles',
	'name' => 'roles',
	'entity' => 'roles',
	'attribute' => 'name',
	'model' => "Backpack\PermissionManager\app\Models\Role",
	'pivot' => true,
]
```

Now, create this file: _/resources/views/vendor/crud/fields/selectRoles.blade.php_
then you paste the contents of the file _select2_multiple.blade.php_ (or select), and then you edit some lines to make it suit you.
I removed the line that added the - hypen. `<!-- <option value="">-</option> -->`
And then removed the `multiple` attribute in the select tag.


You can find more ways to edit this in [this repo](https://github.com/select2/select2).


<img width="780" alt="screen shot 2016-10-25 at 14 48 12" src="https://cloud.githubusercontent.com/assets/4010693/19703751/33bd9354-9ac2-11e6-846f-2da7f6789e14.png">
