### ISSUE TITLE
'Undefined index: permissions' error when i click user edit button

### ISSUE THREAD

**Issue by SEZERKORAYALAKUS** [Laravel-Backpack/PermissionManager#279]
# Undefined index: permissions (View: .....\backpack\crud\src\resources\views\crud\fields\checklist_dependency.blade.php)

### What I did:
I assigned permissions to roles. (ex: super_admin (role): car_update (permission) and car_delete (permission))
Then I clicked the button to edit a user whose role is super_admin.

Edit: I click the button to edit a user with the role

### What I expected to happen:
Opening the user editing screen and making editing

### What happened:
![Ekran Alıntısı](https://user-images.githubusercontent.com/43064380/119625484-e6744380-be12-11eb-8970-6b1d34cab566.PNG)

### What I've already tried to fix it:
I followed the steps in the PermissionManager header but the problem continued.

### Backpack, Laravel, PHP, DB version:
php v: 7.2.19, laravel v: 7.30.4, backpack v: 4.1.43, MariaDB v: 10.6.0-MariaDB

**Comment by pxpm** [comment]
Hello @SEZERKORAYALAKUS 

My guess is that it could be a cache problem ? Please try to run`php artisan cache:clear`.

Let me know,
Pedro

**Comment by SEZERKORAYALAKUS** [comment]
hello @pxpm 
I tried but it didn't solve the problem.
