### ISSUE TITLE
`Undefined array key "model"` when adding roles to a User

### ISSUE THREAD

**Issue by olipayne** [Laravel-Backpack/PermissionManager#291]
# Bug report
Editing a User with the default `UserCrudController` provided by this package now throws a `Undefined array key "model"
` error.
### What I did:
 - Brand new Laravel 9 install
 - Installed Backpack v5
 - Installed PermissionManager `6.0.13`
 - Ran all migrations
 - Created a Permission
 - Created a Role and added the new Permission
 - Tried to assign that Role to a user

### What I expected to happen:
The User to update successfully

### What happened:
https://flareapp.io/share/dmkjLdD5#F60

### Backpack, Laravel, PHP, DB version:
Backpack 5.0, Laravel 9.0, MySQL 8.0

**Comment by pxpm** [comment]
closing in favor of https://github.com/Laravel-Backpack/CRUD/pull/4166 . Already reviewed and ready for merge.

Thanks again @olipayne ! 🙏

**Comment by edrisaturay** [comment]
i still get this error after following the documentation.. I even setup a new project and this error persists.. any help will be highly appreciated..

PHP V 8.1.6 and Laravel 9.19.0

**Comment by pxpm** [comment]
@edrisaturay and what backpack version you are using ? 

Please do: `php artisan backpack:version`

Cheers

**Comment by edrisaturay** [comment]
### PHP VERSION:
PHP 8.1.6 (cli) (built: May 11 2022 08:55:59) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.1.6, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v9.21.5@a1944cd0d160a2cc423ef5a451d002711c5f014f

### BACKPACK VERSION:
5.2.2@bea3042dceb2bd2a888f67d3782908bced33938a

**Comment by olipayne** [comment]
@edrisaturay do you have a stack trace you can share? This issue was pretty nicely solved so it might be a similar but unrelated issue.
