### ISSUE TITLE
6.0.14

### ISSUE THREAD

**Issue by blondie63** [Laravel-Backpack/PermissionManager#298]
Is this version released?
Because on my prj i've 6.0.13 and "composer update" don't upgrade it..

**Comment by pxpm** [comment]
Yes, 6.0.14 is tagged. 

Strange, I could update to it. Don't you have a manual constraint in your `composer.json` ? 

![image](https://user-images.githubusercontent.com/7188159/161294578-0295e2f6-6010-4139-9c2f-d8d1b6aa64a6.png)

**Comment by blondie63** [comment]
my composer.json
    "require": {
        "php": "^7.3|^8.1",
        "backpack/crud": "^5.0.0",
        "backpack/filemanager": "^2.0",
        "backpack/logmanager": "^4.0",
        "backpack/permissionmanager": "^6.0.13",
        "backpack/pro": "^1.0",
        "backpack/settings": "^3.0.15",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "laravel/framework": "^9.0",
        "laravel/sanctum": "^2.11",
        "laravel/tinker": "^2.5",
        "spatie/laravel-translatable": "^5.2.0"
    },
    
running "composer show backpack/permissionmanager" i've same your output, so i think 6.0.14 is installed also if composer.json have 6.0.13, right ?

**Comment by pxpm** [comment]
You are not constraining to 6.0.13, you are constraining to 6.0.13++ . Yes, you have 6.0.14 then. 👍 

Going to close this. 

Cheers
