### ISSUE TITLE
Need to register Spatie's PermissionServiceProvider

### ISSUE THREAD

**Issue by vishalbhide** [Laravel-Backpack/PermissionManager#3]
Hi,

The stock spatie functionality does not work, since their service provider does not get called. Please add the below lines in bold to _Backpack\PermissionManager\PermissionManagerServiceProvider_

**use Spatie\Permission\PermissionServiceProvider;**

class PermissionManagerServiceProvider extends ServiceProvider{
public function register()
    {
        //$this->registerPermissions();
        **$this->app->register(PermissionServiceProvider::class);**
        $this->setupRoutes($this->app->router);
        //use this if your package has a config file
         // config([
         //         'config/laravel-permission.php',
         // ]);
    }
}

**Comment by tabacitu** [comment]
@mariusconstantin2503 ?

**Comment by vishalbhide** [comment]
Hi,

FYI - I had proposed the above approach when I had taken a first look at the backpack framework, and due to lack of usage documentation for permissionmanager. Subsequently I realized that instead of adding the above entry, we can also alternatively add the spatie PermissionServiceProvider package in the providers array in app.php. Generally, I would prefer if backpack does all the dependent provider loading within its own ServiceProviders, instead of asking end-users to configure all the dependencies (like spatie/permissionmanager), but either ways is ok.

// config/app.php
'providers' => [
    ...
    Spatie\Permission\PermissionServiceProvider::class,
];

**Comment by tabacitu** [comment]
No, you're right, your solution is better. One less line in the install process is a very good thing.

For the time being, I've updated the README to include the Spatie service provider (c757b8a78200636819e7039844d7ce676e3147f7), but in a few days I'll go across all Backpack projects and implement your solution. Let's leave the issue open until then.

Cheers!

**Comment by vishalbhide** [comment]
If you are going to go ahead and load the dependent service providers, could you also load please load the dependent aliases as below?

//Load Aliases

`$loader = \Illuminate\Foundation\AliasLoader::getInstance();`

//For base package

`$loader->alias('Alert', \Prologue\Alerts\Facades\Alert::class);`

//For CRUD package
```
$loader->alias('CRUD', \Backpack\CRUD\CrudServiceProvider::class);
$loader->alias('Form', \Collective\Html\FormFacade::class);
$loader->alias('Html', \Collective\Html\HtmlFacade::class);
```

And while we are at it, to further make multi-package installation easier, a suggestion is as below -

1. In backpack/base composer.json, require all backpack packages (and their dependencies by default)

example -

```
"backpack/permissionmanager": "^2.0"
"spatie/laravel-permission": "^1.4",
"backpack/crud": "^2.0.0",
"backpack/generators": "^1.1",
"backpack/langfilemanager": "^1.0",
"backpack/settings": "^2.0",
"caouecs/laravel-lang" : "~3.0"
...
```

2. Add a new config section in backpack/base/config/base.php

```
'enabled_packages' => [
        'crud' => true,
        'generators' => true,
        'settings' => false
 	....
    ], 
```

3. In the base service provider, conditionally load the dependencies for each enabled package

```
if(config('backpack.base.enabled_packages.crud')){
  $this->loadCrudServiceProviderAndDependencies();
}
```

Advantage of this approach -

1. Simpler to implement programmatically, instead of developing a whole new backpack installer
2. Easy configuration for end users and end users need not be aware of the other backpack packages at all, other than the base package.

Drawbacks of this approach -
1. Since all backpack packages and their dependencies are included in the base composer.json, the disk space for the end user's project will be more (should be at least 100 MBs for 1 project, if all packages are included)
2. Even if a user needs to work with only 1 package (e.g. CRUD), still all the backpack packages will get downloaded on a user's machine.

Would be great if there is some way to conditionally require packages in composer.json (I am not aware if such an option exists in composer)

Still, thought I'd suggest this idea, in case this approach holds merit.

**Comment by vishalbhide** [comment]
Thanks, glad you liked it. :) Another, better approach is not to touch the base package at all, but to create a new package called backpack or all, and make this as the add all package, which will include all other packages like base, pagemanager etc. The other existing packages can be left untouched. This will give flexibility to users to pick and choose packages like they currently do, or to use the single add all package if they want.

On another note, in the service providers, can you please move route registrations from the register to the boot method? That will bring things more in line with laravel recommendation to "never attempt to register any event listeners, routes, or any other piece of functionality within the register method"  from https://laravel.com/docs/5.2/providers

**Comment by tabacitu** [comment]
@vishalbhide my thoughts exactly. A separate package that has everything installed has all the advantages you've mentioned and none of the drawbacks. It's simple, it's efficient, that's definitely the way to go!

What should we call it? 
- backpack/example
- backpack/starter
- backpack/complete
- backpack/test

None sound very good to me. Any other ideas?

**Comment by vishalbhide** [comment]
Choosing a good name is more difficult than writing code :)

A few that come to mind

backpack/whole
backpack/full
backpack/ultimate
backpack/fusion

backpack/coco (Abbreviate for COmplete COllection)
backpack/whose (Abbreviate for WHole Set)

or something totally unrelated?
backpack/aurora
backpack/hydra

**Comment by Ghitu** [comment]
backpack/kickstarter
backpack/all-in
--

Andrei Iordache
Creative Director & Co-Founder

m: +40 732 512 067
e: andrei@updivision.com
w: www.updivision.com

25 C.A. Rosetti Street
District 2, Bucharest, Romania

**Comment by tabacitu** [comment]
Hmmm... So far I think I like these best:
- backpack/full
- backpack/cms - isn't this what it is, actually, if you install all packages? A CMS for basic websites? PyroCMS v3 just launched and it's pretty much this, only with questionable UI and some more features (streams, notably);

Thoughts?

**Comment by vishalbhide** [comment]
I don't think backpack should be marketed as a cms just yet, as that might raise end-user expectations - there are a few missing components/widgets like multi-language model support, sample frontend templates, galleries, basic contact form etc. As that gets added, it will be closer to a standard cms.

Maybe 2 packages could be created? backpack/full with everything excluding News and Article CRUD, and backpack/cms which includes News & Article, as well as additional components that will get added in the future?

**Comment by tabacitu** [comment]
Hmm... you may be onto something with the missing functionality to call it a CMS. Also, the CMS term has gained some negative connotation lately, better to stay away from it.

Pretty sure 2 packages is overkill. 1 package with everything installed should do.

Ok then, it's now between:
- backpack/full
- backpack/backpack (similarly to how laravel has its main package laravel/laravel)

Final list. Thoughts?

**Comment by tabacitu** [comment]
I just realised that I might have gotten excited about this solution a bit early. This all-in-one package won't be used only for testing Backpack, people will use it in production, because we're lazy and we take shortcuts - let's face it. So this will result in people having installed packages that they don't actually use, which is a very bad practice.

I think the best way to go here is to not take shortcuts:
**1) For production use** - Backpack/base will have a command-line installation wizard, which asks which packages you want and automatically publishes views, configs, registers service providers, runs migrations, etc. I hope [this package](https://github.com/terion-name/package-installer) will make it faster to implement.
**2) For testing Backpack** - a Laravel instance with all packages installed, called backpack/demo. This way, it's easy to test, but it's obviously not for production use.

**Comment by vishalbhide** [comment]
Ok. backpack/demo option is good as well.
