### ISSUE TITLE
Target class [hash] does not exist.

### ISSUE THREAD

**Issue by cod3rshotout** [Laravel-Backpack/PermissionManager#313]
I added in my controller this code within the constructor:

    backpack_user()->hasPermissionTo('administration');

now when I load the page I get:

>Target class [hash] does not exist.

check the attachment
![hash](https://user-images.githubusercontent.com/72454584/201321995-acf7dab9-a15b-422c-9833-07e1a0ee0ee3.jpg)

**Comment by pxpm** [comment]
Hello @cod3rshotout 

I cannot help much here, but I think the problem might be on `AsiPageCrudController`  `__construct()` from the error trace you posted. 

I can try to help you more if you could share a flare error page or something that I could have a look. 

I am going to close this as I think this is an implementation issue, but I may be wrong, so feel free to re-open or keep the discussion if needed and I will try my best to help. 

Cheers
