### ISSUE TITLE
Password field is rendering encrypted password from DB in User's CRUD

### ISSUE THREAD

**Issue by karandatwani92** [Laravel-Backpack/PermissionManager#318]
#### Pre-filled Password field:
![Screenshot 2022-12-21 at 9 00 49 PM](https://user-images.githubusercontent.com/8214221/208942182-0833a4f8-54bc-4a8a-b062-79e7de797ac4.png)
#### Inspect element:
![Screenshot 2022-12-21 at 9 00 19 PM](https://user-images.githubusercontent.com/8214221/208942096-e6b40ab3-951b-4f2a-ac4c-42e9d66e1415.png)

**Comment by tabacitu** [comment]
Fixed in https://github.com/Laravel-Backpack/CRUD/pull/4857. Good find, Karan!
