### ISSUE TITLE
SQLSTATE[HY093]: Invalid parameter number

### ISSUE THREAD

**Issue by nordic-digit** [Laravel-Backpack/PermissionManager#324]
# Bug report
I am getting this error when i am clicking on roles. permissions works fine. i can create new roles but i always get this error, when i am in the list view. even when i have complete empty roles table. here is the full error:

```sql
select count(*) as total_rows from (select `roles`.`id`, (select count(*) from `users` inner join `model_has_roles` on `users`.`id` = `model_has_roles`.`model_id` where `roles`.`id` = `model_has_roles`.`role_id` and `model_has_roles`.`model_type` = ? and `users`.`deleted_at` is null) as `users_count` from `roles`) as `roles_aggregator`
```

i already tried to reinstall everything i tried it in a complete new laravel enviroment. nothing helped.

i am using laravel 9.11 with php 8.0.2 and backpack 5.0

**Comment by pxpm** [comment]
Hey guys!

Thanks for the report @nordic-digit !

We found out the issue you described in the `Backpack\CRUD` repository and fixed it there.

It should be working fine on 5.5.7 . Please do a `composer update backpack/crud` to get the latest version.

Cheers 🙏
