### ISSUE TITLE
PermissionManager failing to install on backpack v6

### ISSUE THREAD

**Issue by onktak** [Laravel-Backpack/PermissionManager#329]
# Bug report

Ran composer require backpack/permissionmanager

Am getting incompatibility errors

  Problem 1
    - backpack/permissionmanager[1.0.1, ..., 1.0.4, 2.0.0, ..., 2.1.20] require illuminate/support ~5.1 -> found illuminate/support[v5.1.1, ..., v5.8.36] but these were not loaded, likely because it conflicts with another require.
    - backpack/permissionmanager[2.1.21, ..., 2.1.26] require backpack/crud ^3.3.0 -> found backpack/crud[3.3.0, ..., 3.6.x-dev] but it conflicts with your root composer.json require (v6.x-dev).
    - backpack/permissionmanager[2.1.27, 3.12.0, ..., 3.12.6, 4.0.0, ..., 4.0.6] require backpack/crud ^3.4.0 -> found backpack/crud[3.4.0, ..., 3.6.x-dev] but it conflicts with your root composer.json require (v6.x-dev).
    - backpack/permissionmanager[4.0.1, ..., 4.0.3] require backpack/crud ^3.4.0|dev-upgrade -> found backpack/crud[3.4.0, ..., 3.6.x-dev] but it conflicts with your root composer.json require (v6.x-dev).
    - backpack/permissionmanager[5.0.0, ..., 5.0.7] require backpack/crud ^4.0.0 -> found backpack/crud[4.0.0, ..., 4.1.x-dev] but it conflicts with your root composer.json require (v6.x-dev).
    - backpack/permissionmanager[6.0.0, ..., 6.0.11] require backpack/crud ^4.1.0 -> found backpack/crud[4.1.0, ..., 4.1.x-dev] but it conflicts with your root composer.json require (v6.x-dev).
    - backpack/permissionmanager[6.0.12, ..., 6.0.16] require backpack/crud ^5.0 -> found backpack/crud[5.0.0, ..., 5.6.1] but it conflicts with your root composer.json require (v6.x-dev).
    - Root composer.json requires backpack/permissionmanager * -> satisfiable by backpack/permissionmanager[1.0.1, 1.0.2, 1.0.3, 1.0.4, 2.0.0, ..., 2.1.27, 3.12.0, ..., 3.12.6, 4.0.0, ..., 4.0.6, 5.0.0, ..., 5.0.7, 6.0.0, ..., 6.0.16].

### Backpack, Laravel, PHP, DB version:

 "require": {
        "php": "^8.1",
        "backpack/crud": "v6.x-dev",
        "backpack/pro": "v6.x-dev",
        "backpack/theme-tabler": "dev-main",
        "guzzlehttp/guzzle": "^7.2",
        "ivanomatteo/laravel-device-tracking": "^0.2.1",
        "laravel/framework": "^10.10",
        "laravel/sanctum": "^3.2",
        "laravel/tinker": "^2.8",
        "nwidart/laravel-modules": "^10.0",
        "owen-it/laravel-auditing": "^13.5"
    },
    "require-dev": {
        "backpack/generators": "v6.x-dev",
        "fakerphp/faker": "^1.9.1",
        "laravel/pint": "^1.0",
        "laravel/sail": "^1.18",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^7.0",
        "phpunit/phpunit": "^10.1",
        "spatie/laravel-ignition": "^2.0"
    },

**Comment by tabacitu** [comment]
Please try the v6-compatible version:
```
composer require backpack/permission-manager:"v6.x-dev"
```

Let us know if that doesn't work and we'll re-open. But I'm pretty sure it will 😉

**Comment by onktak** [comment]
It works. 

Please correct command to :  **composer require backpack/permissionmanager:"v6.x-dev"**

Thanks for the quick fix.
