### ISSUE TITLE
Can not open menu admin/user

### ISSUE THREAD

**Issue by mytrix-technology** [Laravel-Backpack/PermissionManager#33]
Hi Cristian Tabacitu,
I have a problem after installation plugin backpack laravel.
If I access menu admin/user, I have an error like this "Call to undefined method Illuminate\Database\Query\Builder::addFakes()". 
I'm not found where is the problem. 
I've seen at config in folder vendor/backpack/permissionmanager,
Can you solve this issued??

**Comment by tabacitu** [comment]
Hi. I'm pretty sure you forgot to add the CrudTrait on your User model.

Cheers!

**Comment by mytrix-technology** [comment]
Okay. 
Now I have an error like this "Call to undefined method Illuminate\Database\Query\Builder::roles() (View: G:\wampstack55\apache2\htdocs\backpack-laravel\resources\views\vendor\backpack\crud\columns\select_multiple.blade.php) (View: G:\wampstack55\apache2\htdocs\backpack-laravel\resources\views\vendor\backpack\crud\columns\select_multiple.blade.php)".

This is my user model : 
**<?php

namespace App;

use Backpack\CRUD\CrudTrait;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use CrudTrait;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}**

**Comment by tabacitu** [comment]
Please follow the installation steps more carefully. It seems to me like you haven't done step 4 at all.

https://github.com/Laravel-Backpack/PermissionManager/blob/master/README.md

Cheers!

**Comment by mytrix-technology** [comment]
Thanks. I missed 1 step. Sorry before
