### ISSUE TITLE
Users can still access the url if they have permisison

### ISSUE THREAD

**Issue by medeepaksaini** [Laravel-Backpack/PermissionManager#338]
# Bug report

### Backpack, Laravel, PHP, DB version: 6, 10, 8.2

If we have set the permission/ role we can still access data using URL, same issue in Laravel Backpack demo also.

**Comment by tabacitu** [comment]
Hi @medeepaksaini ,

That's normal. This package does NOT limit access, according to the roles or permissions you've added. It would be impossible to do so, we have no way of knowing what roles or permissions you added. This package is just a way to add/edit/delete entries in the Roles and Permissions tables in the database, nothing more.

**After you've added roles and permissions to your database, you have to code the limitations yourself**, depending on what roles and permissions you have. Use the spatie/laravel-permission API for that. We've made a quick copy-paste for you here - https://github.com/Laravel-Backpack/PermissionManager#api-usage

Hope it helps.
Cheers!
