### ISSUE TITLE
Upgrade to `spatie/laravel-permission` v6.1

### ISSUE THREAD

**Issue by callmejed** [Laravel-Backpack/PermissionManager#347]
I'm using Spatie ^6.1 so composer require fails since this package seems to require Spatie ^5.0

**Comment by promatik** [comment]
Hi @callmejed!

I've read the upgrade guide and it seems there was a lot of changes/possible breaking changes.
https://github.com/spatie/laravel-permission/blob/main/docs/upgrading.md#upgrading-from-v5-to-v6

We're probably work this out for the new backpack version.

**Comment by tabacitu** [comment]
![cat-glasses-gif-by-leroy-patterson](https://github.com/Laravel-Backpack/PermissionManager/assets/1032474/f2063492-66b3-4794-82e6-dc361cc114ed)

We should be able to add support for `spatie/laravel-permission` v6, it has nothing to do with `backpack/crud`. We can do this:
- `backpack/permissionmanager` v7 will support `spatie/laravel-permission` v3, v4, v5
- `backpack/permissionmanager` v8 will support only `spatie/laravel-permission` v6

So yeah, I'd stay we should prioritize and do this, if people use the latest PermissionManager they can't add this Backpack add-on on top.

**Comment by callmejed** [comment]
That would be fantastic <3

**Comment by promatik** [comment]
This one was fixed by @pxpm 3 weeks ago 🎉
https://github.com/Laravel-Backpack/PermissionManager/pull/356
