### ISSUE TITLE
Orderable on columns of type custom_column has not been disabled

### ISSUE THREAD

**Issue by tringuyenduc2903** [Laravel-Backpack/PermissionManager#357]
# Bug report

### What I did:

Test the sort operation on the entire column

### What I expected to happen:

Sort successfully

### What happened:

![image](https://github.com/Laravel-Backpack/PermissionManager/assets/101564593/9a9732f0-0c53-40cb-b458-af8d9ff7e7a1)
1. **Roles**, **Extra** in **Users**
![image](https://github.com/Laravel-Backpack/PermissionManager/assets/101564593/da345fc7-1183-4bd7-accd-8618f652d682)

2. **Permissions** in **Roles**
![image](https://github.com/Laravel-Backpack/PermissionManager/assets/101564593/a40bb10d-49a6-45ac-9a99-cd2e7ee5e42b)

### What I've already tried to fix it:

```php
 // Add attribute to column
 'orderable' => false
```

### Backpack, Laravel, PHP, DB version:
![image](https://github.com/Laravel-Backpack/PermissionManager/assets/101564593/4c8485ac-926d-47d9-afc0-ec23f1b8aa7d)

**Comment by promatik** [comment]
Hey @tringuyenduc2903!

Can you give us some code sample of your controller?
I tried to disable columns order by setting `'orderable' => false,` and everything worked as expected.
