### ISSUE TITLE
Backpack error : Array to string conversion when I click preview(show) user

### ISSUE THREAD

**Issue by mliling** [Laravel-Backpack/PermissionManager#359]
# Bug report
I got this issue and I took much time but i still couldn't fix this error. I have tried to hide the preview button but the solution doesn't work.
### What happened:
![image](https://github.com/Laravel-Backpack/PermissionManager/assets/41537886/68d8f29f-d5d3-4cc9-9716-cd7b23d74714)

### What I've already tried to fix it:
 I used this **CRUD::denyAccess('show');** or **$this->crud->removeButton('show');** in **setup()** or **setupListOperation()**. But it still can't help.

### Backpack, Laravel, PHP, DB version:
PHP 8.2.13
Laravel Framework 10.46.0
DB MySQLServer 8.2.0
### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.3.4
backpack/crud: v6.x-dev
backpack/generators: v4.0.4
backpack/permissionmanager: 7.2.0
backpack/theme-tabler: 1.2.5

**Comment by karandatwani92** [comment]
Hey @mliling 

I hope you are already extending UserCrudController. Here is how I do it:
```php
<?php
// app/Http/Controllers/Admin/UserCrudController.php
namespace App\Http\Controllers\Admin;

use Backpack\PermissionManager\app\Http\Controllers\UserCrudController as CrudController;

class UserCrudController extends CrudController
{
    public function setup()
    {
        parent::setup();
        $this->crud->denyAccess(['show']);
    }
}
```
