### ISSUE TITLE
help me 

### ISSUE THREAD

**Issue by bastha** [Laravel-Backpack/PermissionManager#36]
I have no idea how to set permission manager .. i installed permission manager accordingly...
every things are ok but it doesnot work ... i havent make any controller or set routes.... i only done what it said in page..

help me... somehow i manage to set pages and menu item  in frontend...
now i am stuck in permission manager..

thank you..

**Comment by tabacitu** [comment]
Hi @bastha ,

Sure, tell me what doesn't work, so I can help. Please explain what you did, what you expected to happen and what did/did not happen.

Cheers!

**Comment by bastha** [comment]
Thank you very much for you response ...
Recently I was assign for a work to install Laravel with permission manager
..I am very new in this field so, I don't know where to set route or to
create controller. I install permission manager as well as spatie Laravel
manager . Roles ,permission are also shown in backpack dashboard , I assign
some roles and permission to user ,but it doesn't work like that, it
permits everybody to edit delete update etc activity however I disallow to
some user.   It doesn't work please help me ...Sorry for this problem,
thank you.

**Comment by OwenMelbz** [comment]
You have to handle the permissions yourself, try using middleware. If you search the backpack github issues you'll find lots of people's suggestions how :)

**Comment by bastha** [comment]
my middleware..

<?php

namespace App\Http\Middleware;

use Closure;

class RoleMiddleware {
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
       public function handle($request, Closure $next, $role, $permission)
    {
        if (Auth::guest()) {
            return redirect($urlOfYourLoginPage);  //////i am confused
here//should i leave this variable as it is or should i write the url of
login admin::::::
        }

        if (! $request->user()->hasRole($role)) {
           abort(403);
        }

        if (! $request->user()->can($permission)) {
           abort(403);
        }

        return $next($request);
    }
}

**Comment by tabacitu** [comment]
Hi @bastha ,

I personally like the recommended middleware by spatie (the ones who created the package that permissionmanager uses): https://github.com/spatie/laravel-permission#using-a-middleware

If you follow their instructions you should be able to quickly create two middleware: role and permission, that you can use in your routes file.

A faster way to create those is coming in the near-future in Backpack. This, in combination with Laravel's 5.4 release, will make it a more powerful and intuitive tool, since you'll be able to specify middleware on each route.

Cheers!

**Comment by yingdongzhang** [comment]
@bastha 

I found that the line

```
if (Auth::guest()) {
            return redirect($urlOfYourLoginPage);
        }
```

doesn't really do anything, leaving it there or commenting it out doesn't have any effect. If you have not logged in, you will be directed to the login page anyway, I think Backpack takes care of redirecting guests before they enter this middle. If you have logged in already, it won't enter the `if` statement. So I think it is safe to remove the if statement completely.

**Comment by tabacitu** [comment]
@yingdongzhang - totally agree.

@bastha , if you haven't figured this out yet, [here's the code to my middlewares](https://gist.github.com/tabacitu/acd7929cc9f60d104da1df4c39f0dad2). Hope it helps.

Cheers!
