### ISSUE TITLE
Each user access to admin panel by default!

### ISSUE THREAD

**Issue by bahman2216** [Laravel-Backpack/PermissionManager#37]
It there any way to prevent access other users to admin panel?
I made roles for user and admin, But there is no gui mode to assign role to user.

**Comment by OwenMelbz** [comment]
Hi, I'm not 100% what you mean sorry.

Are you saying that normal front end users can access the admin, and how can you prevent this?

**Comment by bahman2216** [comment]
With permission manager you can create user. But user can access admin panel!
There is no role to check user has access to admin route or not.

**Comment by OwenMelbz** [comment]
Sure, you need to create middleware on your application to filter out users without the correct permissions.

If you search the backpack github both in crud and here you'll find lots of examples of this question already. 90% of them use middleware or guards

**Comment by bahman2216** [comment]
I know, But I mean all CRUD routes has both **"web"** and **"admin"**  middlware.
I can change original source code to remove **"web"** middlware. But I do not want to do this. Im looking for better way.

**Comment by OwenMelbz** [comment]
You dont need to do that.

Just create your own middleware that checks your user is an admin.

The backpack admin middleware is less than perfect, it just checks if they're logged in I think.

You can follow the instructions by spatie - as this is what the permission manager

https://packagist.org/packages/spatie/laravel-permission#user-content-using-a-middleware

**Comment by bahman2216** [comment]
I read the doc and made my custom middlware.
But all routes in service providers Backpack has web **middlware** by default and I could not overide them.
For instance, 

> /admin/page

 has both admin and web middlware and my route middlware did not affect on this route.

**Comment by OwenMelbz** [comment]
you do not need to overwrite the `web` and `admin` middleware.

You can just add your own middleware on top.

You can assign middleware to whole route groups.

You can also define the routes yourself if you do not want the service providers inside the vendor folder

**Comment by OwenMelbz** [comment]
My personal opinion is the fact that session sharing between any generic users is wrong.

e.g If you're logged in to the admin, you're also logged into the frontend, which is highly unpractical I've found, as admins might not be frontend users, for example we have one application where users must belong to a school. But admins will not, meaning you cannot use the frontend and admin at the same time.

I think we need to implement an `backpackAdmin` guard on backpack itself, which allows the separation.

We could publish this middleware which will run default checks against the guard, then users can expand this middleware to handle their custom functionality, which might be role or permission based.

**Comment by tabacitu** [comment]
Damn. You may be right, some projects will have zero functionality on the front-end for the admin. Others, however, will allow him to still use the app as a user (think SaaS, forum, etc). So it's a little trickier than I expected... WIll think about it and get back to you.

**Comment by OwenMelbz** [comment]
I think it could potentially be pretty simple, although would not be fully backwards compatible, and a fair amount of files to change

within the config we would need a setup like

```php
return [

    'separate_admin_session' => true,
    'admin_guard' => [
            'name' => 'backpackAdmin',
            'driver' => 'session',
            'provider' => 'users',
        ],
];
```

then we create the middleware something like

```php
public function handle($request, Closure $next, $guard = null)
{
    if (config('backpack.separate_admin_session')) {
        if (!\Auth::guard(config('backpack.admin_guard.name'))->check()) {
            return redirect(config('backpack.admin_path').'/login');
        }
    }
    
    return $next($request);
}
```

We'd also need to inject the middleware into `$routeMiddleware` within the `Kernal.php` however not really sure how to go about doing this, i guess in the service provider somhow

We'd then also need to make sure all the auth classes define the class e.g. in the LoginController we'd need

```php
public function guard()
{
    return \Auth::guard(config('backpack.admin_guard.name'));
}
```

We would then also need to update all the templates / classes that do things like

`Auth::check()` or `Auth::user()` to `Auth::guard(config('backpack.auth_guard.name'))->user()` 

It does seem a fair amount of work and extra code, but I think its a definitely worth feature!

**Comment by OwenMelbz** [comment]
Ended up adding a PR for this https://github.com/Laravel-Backpack/Base/pull/87

**Comment by lloy0076** [comment]
Please see the PR https://github.com/Laravel-Backpack/Base/pull/87.
