### ISSUE TITLE
Checkboxes vs Radio in role assignments

### ISSUE THREAD

**Issue by sonoftheweb** [Laravel-Backpack/PermissionManager#38]
Hi guys,

I was thinking, is it not wise to have radios as opposed to checkboxes when assigning roles to a user? Is there a way to do this without affecting ability to update?

**Comment by OwenMelbz** [comment]
What's your theory on having radios?

I think checkboxes make sense as you would need 2 radios for each role. 1 to say yes, 1 to say no.

Where as a checkbox has a yes/no state in 1 element?

**Comment by sonoftheweb** [comment]
I understand. I will just have to use JQuery to make sure that only one is selected at a time. Do you think that is something that can be added to the system, just incase we are rooting to assign one user per role?

**Comment by tabacitu** [comment]
Hi @sonoftheweb ,

I think it would be too restrictive to push this into the main package. Most systems allow for multiple roles per user. 

Also on this topic, remember you can check how many roles have been selected using the form request validation - it could be your "second layer" that informs the admin why he can't select multiple roles.

Cheers!
