### ISSUE TITLE
Overriding package controllers to add new fields to the user table

### ISSUE THREAD

**Issue by sonoftheweb** [Laravel-Backpack/PermissionManager#39]
Is there a way one can Override the package controller (say UserCrudController.php) with the same file created in App/Http/Controllers/Admin? The reason being that I want to add some more columns to the table with extra data without breaking anything when updates are made.

**Comment by OwenMelbz** [comment]
You'd need to copy out all the user controllers into your app folder and define the routes yourself.

It would mean if updates are made you'd have to manually apply them.

But that's normal - if you want to change core functionality then you'll have to do it yourself.

I personally don't bother with the built in user controller. It's hardly much work doing it yourself. More control and better practice :)
