### ISSUE TITLE
How to make this work with crud?

### ISSUE THREAD

**Issue by axyr** [Laravel-Backpack/permissionmanager#4]
Im trying the field examples on 

https://laravel-backpack.readme.io/docs/crud-fields

to create something like this:

https://camo2.githubusercontent.com/e442e4819b19e196ee37e53331bac52d5a4f7a8d/68747470733a2f2f646c2e64726f70626f7875736572636f6e74656e742e636f6d2f752f323433313335322f6261636b7061636b5f7065726d697373696f6e6d616e616765725f757365722e706e67

**Comment by tabacitu** [comment]
I'm sorry, I don't understand. What's not working?

**Comment by tabacitu** [comment]
Oooh, I understand now. You're saying there's no documentation for that the checklist and checklist_dependency field types.

You're right, thank you for the issue, the documentation has been updated with the basic field attributes. Check out https://laravel-backpack.readme.io/docs/crud-fields#checklist_dependency
