### ISSUE TITLE
Users list ignoring soft deletes?

### ISSUE THREAD

**Issue by datune** [Laravel-Backpack/PermissionManager#40]
The list view for users seems to completely ignore soft deletes, as such showing deleted users as well. Is this intentional?

**Comment by datune** [comment]
Yes of course it has the required fields.

**Comment by tabacitu** [comment]
Hi @datune ,

Sorry you're having issues, but I just tried it on 3 instances and I can definitely confirm soft deletes are working properly, on the User model and any other model that has a CRUD Panel.

So... it's not me, it's you :-)

Take a closer look at [Laravel's soft deleting documentation](https://laravel.com/docs/5.4/eloquent#soft-deleting), you might have missed something. Happens all the time. I'll close this issue, but if you reply with what you've already done, we can probably help you debug it. 

Cheers!
