### ISSUE TITLE
Config for disable permission and role delete???

### ISSUE THREAD

**Issue by yingdongzhang** [Laravel-Backpack/PermissionManager#41]
Why are there no settings for disabling delete on permission and role? This seems quite an obvious feature. Is this intentional?

```
'allow_permission_delete' => true,
```

```
if (!config('backpack.permissionmanager.allow_permission_delete')) {
    $this->crud->denyAccess('delete');
 }
```

**Comment by yingdongzhang** [comment]
Ended up creating a pull request:

https://github.com/Laravel-Backpack/PermissionManager/pull/42

**Comment by tabacitu** [comment]
Merged the PR, thank you!
