### ISSUE TITLE
Restrict access to Permission Manager

### ISSUE THREAD

**Issue by CHOMNANP** [Laravel-Backpack/PermissionManager#44]
Let say we have "Admin" and "User" role in our application.
I manage to create a custom middle and grant access to a route for specific role only.

`Route::group(['prefix' => 'admin', 'middleware' => 'admin','middleware' => 'hasRole:admin'], function()
{
    CRUD::resource('data', 'Admin\DataCrudController');
}
`

This is my middleware

`<?php
namespace App\Http\Middleware;
use Closure;
use Auth;
use Alert;
class HasRole
{
    public function handle($request, Closure $next, $role)
   {
       if (!Auth::user()->hasRole($role)) {
            Alert::add('error', 'You do not have necessary authorization to access to the page')->flash(); 
            return redirect('home');
       }
       return $next($request);
   }
}`

By doing this, only user with "admin" role shall allow to access to the route "data".

Yet, I also want to restrict route "/admin/user" and "/admin/role", which is generated by this package, for "admin" user only.

Anyone has experience with this?

Thanks,
Punleu

**Comment by OwenMelbz** [comment]
You can disable the default routes from the config.

Then you can copy/paste the routes from the permissionmanager service provider into your protected route group

**Comment by CHOMNANP** [comment]
Thanks :)
Solved.

**Comment by sbaluha** [comment]
How do you disable the default routes from the config?
Also what would the routes look like in my own route group?

I don't see anywhere in documentation or the code a way to disable the default routes and nowhere do I see routes to copy in permissionmanager, I see them in PermissionManagerServiceProvider but I had trouble trying to get them to work.

**Comment by sbaluha** [comment]
Ok, I figured out how to restrict users from accessing the user/roles/permissions CRUD pages.
Here is a folder with all the files modified to do it: [Restrict.zip](https://github.com/Laravel-Backpack/PermissionManager/files/784143/Restrict.zip)

Here's how I did it:
I took the CrudControllers and PermissionManagerServiceProvider from the backpack/permissionmanager vendor folder and put them into my normal project folders.
Then I modified those files to fit the current structure (Namespace and file locations changed).
After that I modified my routes file to access the new crud controllers and commented out the routes in the PermissionManagerServiceProvider.
I also added the ability to use env file variables to turn on/off the CRUD for user/role/permissions in the permissionmanager config file.

Voila!  Now you can restrict that CRUD to a certain group of users :)

**Comment by baj84** [comment]
Hey @sbaluha What did you use for your middleware? It's not in the zip file.

**Comment by sbaluha** [comment]
Updated the zip here: [Restrict.zip](https://github.com/Laravel-Backpack/PermissionManager/files/1019071/Restrict.zip)

**Comment by cdarken** [comment]
@OwenMelbz can you please give more details how we can disable the default routes from the config?

**Comment by OwenMelbz** [comment]
Its explained in the docs https://laravel-backpack.readme.io/docs/frequently-asked-questions#section-customizing-the-auth-controllers

**Comment by cdarken** [comment]
Thanks, I didn't see any conditions in PermissionManagerServiceProvider::setupRoutes and I realized that I had to upgrade my packages.
