### ISSUE TITLE
Unable to edit user, system assumes primary key is id.

### ISSUE THREAD

**Issue by l3rady** [Laravel-Backpack/PermissionManager#46]
The issue here might be in the CRUD package and not this one, but I'm only seeing this error in this package.

When I go to edit a user `admin/user/1/edit` I get the following error.

```
ErrorException in Connection.php line 770:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'where clause' (SQL: select * from `users` where `id` = 1 limit 1)
(View: ***/vendor/backpack/crud/src/resources/views/fields/checklist_dependency.blade.php)
(View: ***/vendor/backpack/crud/src/resources/views/fields/checklist_dependency.blade.php)
(View: ***/vendor/backpack/crud/src/resources/views/fields/checklist_dependency.blade.php)
```

Something somewhere is hard coding that the primary key is `id` but in my case, it is `user_id`.

In the checklist_dependency field if I hard code from `id` to `user_id` in the where statement the edit view works but when I go to save I get a 404 at `/admin/user/1` with `No query results for model [App\Models\User]`. Currently, I cannot find where things are going wrong here.

**Comment by l3rady** [comment]
In `checklist_dependency.blade.php`

if I change line 31:

```
->where('id', $id)
```

to:

```
->where($entity_model->getKeyName(), $id)
```

should fix this field to work with any primary key set on the model being used. I can see a lot of use of `id` further in the view that may not work when working with other relationships that don't have a standard primary key of `id`

**Comment by OwenMelbz** [comment]
Nice spot, I guess you can now that PR going!

Looks like its in a different repo https://github.com/Laravel-Backpack/CRUD/blob/master/src/resources/views/fields/checklist_dependency.blade.php

Everybody should be able to see the Edit button to submit it

![crud_checklist_dependency_blade_php_at_master_ _laravel-backpack_crud](https://cloud.githubusercontent.com/assets/1094740/22464039/ccfc10ae-e7ac-11e6-8a34-ecfa52b88161.jpg)

**Comment by l3rady** [comment]
@OwenMelbz Happy to do a pull request but want to make sure it is complete as I feel like there is more to fix in that view.

**Comment by OwenMelbz** [comment]
Awesome :D well I think tabacitu would have fixed anything else he knew about, so if you can see more issues in there then I think he'd definitely appreciate the effort of submitting a PR as 1 man supporting a project with so many people coming in for support, the more people who can help out and submit PR to fix things the better :)

**Comment by l3rady** [comment]
PR created https://github.com/Laravel-Backpack/CRUD/pull/405

I still have the problem of the 404, cannot track down where this is failing

**Comment by tabacitu** [comment]
Hi @l3rady  - still having the 404 problem?

**Comment by l3rady** [comment]
@tabacitu no. One of my work colleagues found a hard coded id in this package. I will create a pull request tomorrow to fix.

**Comment by tabacitu** [comment]
Oh, sorry to hear that. And happy to hear about the PR :-)
Thanks, cheers!

**Comment by l3rady** [comment]
@tabacitu pull request https://github.com/Laravel-Backpack/PermissionManager/pull/53
