### ISSUE TITLE
List All Users with particular role?

### ISSUE THREAD

**Issue by karandatwani92** [Laravel-Backpack/PermissionManager#47]
How to get Users with particular role?
unable to find such method

i want to count them.

**Comment by OwenMelbz** [comment]
The permissions are all handled by https://github.com/spatie/laravel-permission 

So anything that package provides you can hook into to filter your users.

You can then apply that logic using the where clauses from the docs https://laravel-backpack.readme.io/docs/crud-full-api#section-usage-level-2-often

If you scroll down to the example where it shows some example usage of the "where clauses"

additionally googling suggested some things like https://laracasts.com/index.php/discuss/channels/general-discussion/how-do-i-get-all-users-with-roles-where-role-admin-using-eloquent-along-with-entrust which similar logic can be used

**Comment by karandatwani92** [comment]
Thanks

**Comment by karandatwani92** [comment]
Thanks

**Comment by letscms** [comment]
This can be use also as:
$admins = User::withRole('admin')->get();

Where admin is role name.
It works for me on laravel 5.7
