### ISSUE TITLE
too long time to load user page

### ISSUE THREAD

**Issue by terrainwax** [Laravel-Backpack/PermissionManager#49]
when i want to load user page it's make this FatalErrorException in Arr.php line 185:
Maximum execution time of 30 seconds exceeded

**Comment by terrainwax** [comment]
i have more than 1OOOO users on my website

**Comment by luchaos** [comment]
it seems the users list is not paginating.
takes several seconds to load 2000 users for me

**Comment by tabacitu** [comment]
Hi @luchaos , @terrainwax  ,

You're right, ajax tables should be enabled by default for the Users CRUD. Just pushed an update doing that. ```composer update``` should fix it for your.

Cheers!
