### ISSUE TITLE
Publish vendor has no effects

### ISSUE THREAD

**Issue by welcoMattic** [Laravel-Backpack/permissionmanager#5]
Hi!

I install the package, and when I launch 

```bash
$ php artisan vendor:publish --provider="Backpack\PermissionManager\PermissionManagerServiceProvider"
```

The output is :

```bash
Nothing to publish for tag [].
```

Is there any bug?

**Comment by ptondereau** [comment]
Hello @welcoMattic 

It worked for me with a fresh install. Maybe assets are already published ?

**Comment by tabacitu** [comment]
Hi @welcoMattic !

I'm pretty sure you haven't done the second step in the installation: registering the provider in your config/app.php:
```
Backpack\PermissionManager\PermissionManagerServiceProvider::class,
```

Maybe forgot to hit Ctrl+S? Happens to the best of us! :-)

Cheers!

**Comment by welcoMattic** [comment]
I done it, but I have to clear my config cache ;)
