### ISSUE TITLE
UserCrudController.php allow $this->crud->enableAjaxTable();

### ISSUE THREAD

**Issue by jdfx** [Laravel-Backpack/PermissionManager#52]
I have a large users table and would like to use the Ajax features.

I cannot see a config option for it, forcing $this->crud->enableAjaxTable(); in UserCrudController.php results in a javascript error.

**Comment by jdfx** [comment]
#49

**Comment by tabacitu** [comment]
Hi @jdfx ,

You're right, ajax tables should be enabled by default. Just pushed an update doing that. A ```composer update``` should fix it for your.

Cheers!

**Comment by jdfx** [comment]
You are a superstar. 

Sorry I seem to be opening quite a few issues today. I will try and create some PR's next time when not so busy.

Thank you.
