### ISSUE TITLE
Save and Back/New Button Always Going to /

### ISSUE THREAD

**Issue by lloy0076** [Laravel-Backpack/PermissionManager#55]
[composer.lock.zip](https://github.com/Laravel-Backpack/PermissionManager/files/774879/composer.lock.zip)
[composer.lock.zip](https://github.com/Laravel-Backpack/PermissionManager/files/774884/composer.lock.zip)

For versions I have:

```
  7     "require": {
  8         "php": ">=5.6.4",
  9         "backpack/base": "^0.7.16",
 10         "backpack/crud": "^3.2",
 11         "backpack/permissionmanager": "^2.1",
 12         "laravel/framework": "5.4.*",
 13         "laravel/tinker": "~1.0"
 14     },
```

When I create a user and click on the Save and Back OR Save and New button, I'm always returned to the / (either the index or no slug) URL.

Adding roles/permissions doesn't display this behaviour.

I have the default setup at '/admin' etc (i.e. I haven't changed anything in the `config/backpack directory`).

**Comment by lloy0076** [comment]
[composer.lock.zip](https://github.com/Laravel-Backpack/PermissionManager/files/774886/composer.lock.zip)

**Comment by tabacitu** [comment]
Thank you, just pushed a fix for this. PermissionManager wasn't yet CRUD 3.2-ready, now it is.

Cheers!
