### ISSUE TITLE
Fix Documentation to Use Backpack Base Config

### ISSUE THREAD

**Issue by lloy0076** [Laravel-Backpack/PermissionManager#56]
Documentation links directly to `/admin/[action]` but the `/admin` part is actually configurable and so it breaks when someone has changed it.

The fix that will be suggested in a few hours from now uses the configuration.

**Comment by lloy0076** [comment]
https://github.com/Laravel-Backpack/PermissionManager/pull/57

PS. Contributing.md says I should assign this to myself...but I can't figure out how to do that (probably because I don't have permission to do so).

**Comment by tabacitu** [comment]
Thank you, just merged your fixes to the README.md and fixed the CONTRIBUTING.md too.

Cheers!
