### ISSUE TITLE
installing on laravel 5.6 error

### ISSUE THREAD

**Issue by brazitech** [Laravel-Backpack/PermissionManager#58]
5.4 gives the following error.
also publis does not move the migrate file..had to move by hand.
$ php artisan migrate

  [Illuminate\Database\QueryException]
  SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name '' (SQL: create table `` (`id
  ` int unsigned not null auto_increment primary key, `name` varchar(255) not null, `created_at` timestamp n
  ull, `updated_at` timestamp null) default character set utf8mb4 collate utf8mb4_unicode_ci engine = InnoDB
   ROW_FORMAT=DYNAMIC)

  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name ''

  [PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name ''

**Comment by tabacitu** [comment]
Hi @brazitec ,

Is your project a new one on Laravel 5.4 or have you upgraded? 

I can't seem to get the same error. As far as I know, Laravel 5.4 changes the db collation to ```utf8mb4_unicode_ci``` by default and this can cause some issues if your db was previously ```utf8_unicode```.

Cheers!

**Comment by bloggervista** [comment]
hmm you seem to have wrong migrations check at database/migrations folder if there are any mistyped migrations?

**Comment by lloy0076** [comment]
A) Is this still an issue?
B) What is Laravel **5.6** (is it PHP 5.6?)

**Comment by bloggervista** [comment]
if you are removing columns then please install doctrine dbal package as laravel suggest .
