### ISSUE TITLE
permission_roles doesn't exist

### ISSUE THREAD

**Issue by GigaC** [Laravel-Backpack/PermissionManager#59]
Hello guys, can you help me a little bit.

I am using backpack as an admin panel for this new project and everything is fine. But now I installed this PermissionManager, did everything in **readme** on my current installation which was L5.3, and tried on a fresh new one L5.4

First thing, when I go to the users route **admin/users** it popups me an error (DataTables warning: table id=crudTable - Ajax Error. For more information visit the link), and it doesn't list the users.

Another thing is that when I save the new role I want to create, the system try to save in table that is not there actually :(

What am I doing wrong

**Comment by GigaC** [comment]
I fixed this with renaming the tables in my database. The names of the tables were the keys from the array of the permission config file.

Btw, Great job with the packages

**Comment by bloggervista** [comment]
i guess if you have fixed close this issue :)

**Comment by lloy0076** [comment]
OP fixed 👍
