### ISSUE TITLE
Users list with 'roles and permissions' column

### ISSUE THREAD

**Issue by AurelDragut** [Laravel-Backpack/permissionmanager#6]
Hi,

I added the 'roles_and_permisions' field in the $this->crud->setColumns array, in the UserCrudController, but i can't figure out what i am missing because i don't see what it has been set for the users in that column.

**Comment by tabacitu** [comment]
Hi Aurel,

If you want to see the roles and permissions of a user as columns, use:

```
$this->crud->addColumn([ // n-n relationship (with pivot table)
   'label' => "Roles", // Table column heading
   'type' => "select_multiple",
   'name' => 'roles', // the method that defines the relationship in your Model
   'entity' => 'roles', // the method that defines the relationship in your Model
   'attribute' => "name", // foreign key attribute that is shown to user
   'model' => "Backpack\PermissionManager\app\Models\Roles", // foreign key model
]);
```
and
```
$this->crud->addColumn([ // n-n relationship (with pivot table)
   'label' => "Permissions", // Table column heading
   'type' => "select_multiple",
   'name' => 'permissions', // the method that defines the relationship in your Model
   'entity' => 'permissions', // the method that defines the relationship in your Model
   'attribute' => "name", // foreign key attribute that is shown to user
   'model' => "Backpack\PermissionManager\app\Models\Permission", // foreign key model
]);
```
But please note: this will only show the permission the user has in addition to the permissions attributed to his roles. If you want to list all permissions, you'll need to do it using a method on the user model and [the model_function column type](https://laravel-backpack.readme.io/docs/crud-todo#section-model_function).

**Comment by tabacitu** [comment]
You were right, there is no reason for those columns not to be there - they make the user list view a lot more helpful. Check out 9fa8e682ca78a70f30065715fad43d11aebb7501

Just doing a composer update should pull those changes.

Cheers!

**Comment by AurelDragut** [comment]
Just did the 'composer update'. Excellent job, mate! :)
