### ISSUE TITLE
Config sensible defaults

### ISSUE THREAD

**Issue by bul-ikana** [Laravel-Backpack/PermissionManager#60]
I just noticed that default table names in the migration do not correspond to the index used to look for them in the config files. As an example, `'user_has_permissions'` creates a table called ` 'permission_users'`. 

Is this by design? Is it something inherited from `spatie/laravel-permission`? (couldn't find anything). Is it some kind of widely used convention I am not aware of?

I think the package should provide better defaults, so newcomers have an easier time understanding how this works, but advanced users still can fit to their needs. This can be acomplished either by changing the index name, or the table name. 

What are your thoughts about this?

**Comment by lloy0076** [comment]
@bul-ikana - if you have a PR I'm sure we'd be happy to investigate?

**Comment by lloy0076** [comment]
Please reopen if there is an appropriate PR.
