### ISSUE TITLE
error instalations laravel 5.4

### ISSUE THREAD

**Issue by thavoo** [Laravel-Backpack/PermissionManager#62]
To enable extensions, verify that they are enabled in your .ini files:
    - C:\xampp\php\php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

Installation failed, reverting ./composer.json to its original content.

**Comment by thavoo** [comment]
resolv, the problem it's version php.... thanks

**Comment by domdambrogia** [comment]
Care to elaborate on the PHP versioning? I'm using php 7.x and running into the same problem

**Comment by thavoo** [comment]
Maybe it's other problem.
