### ISSUE TITLE
Adding "levels" to roles

### ISSUE THREAD

**Issue by alashow** [Laravel-Backpack/PermissionManager#66]
Hello.

I'm trying to add the concept of levels to Roles. So when the user has access to user creation/updating, he/she won't be able to create/update higher levels.

For example, if the role "admin" had level 1, and the role "editor" had level 2: user with "editor" role should not be able to create/update/list users with "admin" roles (or levels < 2, or even other "editors").

I started implementing this by adding the "level" field to the database and `RoleCrudController`.

Then I added global scope to `Role` to query roles only which have levels "lower" (in terms of access) than the current user.

But apparently, adding global scope to `Role` has side effects. Currently, my main problem is:
when it checks whether the user has any permission, it goes to [`hasPermissionViaRoles`](https://github.com/spatie/laravel-permission/blob/master/src/Traits/HasRoles.php#L242) function, which queries [`permission->roles`](https://github.com/spatie/laravel-permission/blob/master/src/Models/Permission.php#L38). My global scope is being applied and `hasPermissionTo` returns false.
Also, I couldn't figure out how to validate a request on `onStore/onUpdate` (whether the user has enough role level to assign/to update the given role).

I appreciate any help you can provide!

**Comment by alashow** [comment]
I solved my first issue:
I was using withoutGlobalScope for [`Permission::roles`](https://github.com/spatie/laravel-permission/blob/master/src/Models/Permission.php#L38) only, but forgot to use for [`User::roles`(or `HasRole:roles`)](https://github.com/spatie/laravel-permission/blob/master/src/Traits/HasRoles.php#L148)

**Comment by alashow** [comment]
Solved my second problem too. If anyone interested, I might share it :)

Closing for now.

**Comment by JohnGeigerWS** [comment]
I'm very interested in your solution if you want to share it I'd be quite grateful.
