### ISSUE TITLE
Can't access user details

### ISSUE THREAD

**Issue by AurelDragut** [Laravel-Backpack/permissionmanager#7]
The showDetailsRow requires access to 'details_row' 
`$this->crud->hasAccessOrFail('details_row');`
but
`$this->crud->access` contains only list, create, update, delete.

How can we fix this?

**Comment by tabacitu** [comment]
For future reference:

```
// ------ CRUD DETAILS ROW
$this->crud->enableDetailsRow();
// NOTE: you also need to do allow access to the right users: $this->crud->allowAccess('details_row');
// NOTE: you also need to do overwrite the showDetailsRow($id) method in your EntityCrudController to show whatever you'd like in the details row OR overwrite the views/backpack/crud/details_row.blade.php
```
That IS a little inconvenient, yes. Should we automagically allow access to "details_row" when **$this->crud->enableDetailsRow();** is called? What use case would that prevent? Does it restrict any customization options? The developer will still be able to programatically change who has access to it by encapsulating **$this->crud->enableDetailsRow();** in an if statement. Right?

**Comment by AurelDragut** [comment]
I have kinda hurried with this issue that's why i closed it. It's ok how it is at this moment, but might be a bit tricky when it comes to user profile and details where any changes on the controller must be applied again by us on every update o the permissionmanager package.
