### ISSUE TITLE
Custom UserCrudController

### ISSUE THREAD

**Issue by jhivan** [Laravel-Backpack/PermissionManager#70]
I've modified my `users` table and changed `name` field to `username`, now when i switch to `Users, Roles, Permissions` => `Users` in admin panel i get a `DataTables warning: table id=crudTable - Ajax error. For more information about this error, please see http://datatables.net/tn/7` error. I don't wan to mess with the vendor file (`\Backpack\PermissionManager\app\Http\Controllers\UserCrudController`) and i know in `BackPack\Base` package's config there's an option to customize the auth controllers. I couldn't find the simmilar option in `BackPack\PermissionManager` config. Is editing the vendor UserCrudController my only option?

**Comment by eyemiru** [comment]
Have the same question.
Where can I add fields and change them without changing the vendor file?

**Comment by victorlap** [comment]
I added the following to my routes/web.php to be able to use custom controllers:

This allows me to still use the roles and permission controllers from the package (and everything else), but use a custom UserCrudController


Route::group(['prefix' => config('backpack.base.route_prefix', 'admin'), 'middleware' => ['web', 'admin']], function () {
    CRUD::resource('permission', '\Backpack\PermissionManager\app\Http\Controllers\PermissionCrudController');
    CRUD::resource('role', '\Backpack\PermissionManager\app\Http\Controllers\RoleCrudController');
    CRUD::resource('user', 'Admin\UserCrudController');
});

**Comment by eyemiru** [comment]
Thanks! Just don't forget to change the namespace :)

**Comment by b8ne** [comment]
Can also confirm that this works. Will also need to copy both request files to local project and update namespaces, so that the CRUD model can be correctly validated with updated fields.

**Comment by lloy0076** [comment]
@jhivan - have you found a solution to this issue?

**Comment by tabacitu** [comment]
Hi guys,

Just launched a way easier solution to have a custom UserCrudController. Basically, you can now easily change the routes ([howto here](https://github.com/Laravel-Backpack/PermissionManager#overwriting-functionality)). And if you can change the routes, you can direct the user to your custom UserCrudController.

Hope it helps.

Cheers!
