### ISSUE TITLE
Error on Laravel 5.4.16

### ISSUE THREAD

**Issue by shinokada** [Laravel-Backpack/PermissionManager#72]
I get the following error after `composer require backpack/permissionmanage`

> [InvalidArgumentException]
> Could not find package backpack/permissionmanage at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

How can I solve this problem?

**Comment by tabacitu** [comment]
Hi @shinokada ,

I'm curious - what happened, how did you fix it?

Cheers!

**Comment by shinokada** [comment]
Hi, I installed menuCRUD and I tried it again, and it worked.
