### ISSUE TITLE
Permissions dont work

### ISSUE THREAD

**Issue by Fiftysven** [Laravel-Backpack/PermissionManager#80]
I have a working App with an Backend set up with Backpack. Till now there was no real Authorization check for the Backend, every Backend-User had all rights. Now i wanted to implement Backpack PermissionsManager and everything seemed to work fine. I can create Users, Roles and Permission and with my Middleware i could check if an user has the right Role to access the Backend or parts of it. My only problem is with my Permissions.

This is the Code of my Middleware:

```
namespace App\Http\Middleware;

use Closure;
use Auth;

class RoleMiddleware
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next, $role, $permission)
    {
        if (Auth::guest()) {
            return redirect(url(config('backpack.base.route_prefix').'/login'));
        }
        if (! $request->user()->hasRole($role)) {
            abort(403);
        }
        if (! $request->user()->can($permission)) {
            abort(403);
        }
        return $next($request);
    }
}
```

I made special Admin Routes that can only be accessd if you are an Admin and have the Permission: access_backend.
Now my RoleCheck gets passed and is true, but my Permission check fails. If i give out the needed $permission its 'access_backend' and the permission of the $user is 'access_backend'
(dd(Auth::user()->permissions);). Here i get a Collection of Permissions and the first one is 'access_backend'.

If I try : 
`auth()->user()->role->hasPermissionTo('access_backend');`
I get:
BindingResolutionException in Container.php line 763:
Target [Spatie\Permission\Contracts\Permission] is not instantiable.

Anyone got a clue why my Roles work without an issue but permissions dont seem to work?

**Comment by tabacitu** [comment]
Hi @Fiftysven ,

Does ```auth()->user()->hasPermissionTo('access_backend');``` work?

**Comment by Fiftysven** [comment]
Hi @tabacitu ,

Sadly i get the exact same Error Message:
```
1/1
BindingResolutionException in Container.php line 763:
Target [Spatie\Permission\Contracts\Permission] is not instantiable.
in Container.php line 763
at Container->build('Spatie\Permission\Contracts\Permission', array()) in Container.php line 644
at Container->make('Spatie\Permission\Contracts\Permission', array()) in Application.php line 709
at Application->make('Spatie\Permission\Contracts\Permission', array()) in helpers.php line 106
at app('Spatie\Permission\Contracts\Permission') in HasPermissions.php line 71
at User->getStoredPermission('access_backend') in HasPermissions.php line 21
at User->Spatie\Permission\Traits\{closure}('access_backend', '0')
at array_map(object(Closure), array('access_backend'), array('0')) in Collection.php line 613
at Collection->map(object(Closure)) in HasPermissions.php line 22
at User->givePermissionTo('access_backend') in RoleMiddleware.php line 25
at RoleMiddleware->handle(object(Request), object(Closure), 'Admin', 'access_backend') in Pipeline.php line 137
```
I can post the complete Error Message if it helps and thanks for the fast reply =)

**Comment by lloy0076** [comment]
I setup a backpack with:

* https://gist.github.com/lloy0076/dcb0a74034cc59440395f6ff2310d1d6

Then created a role called 'admin' and 'access_backend' and it works for me.

My composer.json is:

```
1 {
  2     "name": "laravel/laravel",
  3     "description": "The Laravel Framework.",
  4     "keywords": ["framework", "laravel"],
  5     "license": "MIT",
  6     "type": "project",
  7     "require": {
  8         "php": ">=5.6.4",
  9         "backpack/base": "^0.7.18",
 10         "backpack/crud": "^3.2",
 11         "backpack/permissionmanager": "^2.1",
 12         "dompdf/dompdf": "^0.8.0",
 13         "graham-campbell/htmlmin": "^4.5",
 14         "laravel/framework": "5.4.*",
 15         "laravel/tinker": "~1.0"
 16     },
 17     "require-dev": {
 18         "backpack/generators": "^1.1",
 19         "fzaninotto/faker": "~1.4",
 20         "laracasts/generators": "dev-master as 1.1.4",
 21         "mockery/mockery": "0.9.*",
 22         "phpunit/phpunit": "~5.7"
 23     },
```

(there's obviously more than this but the rest isn't needed).

It looks like the IoC container hasn't registered the Spatie permission properly.

Double check if you've added the Backpack permission service provider in your config/app.php like this:

```
Backpack\PermissionManager\PermissionManagerServiceProvider::class,
```

And make sure to either get rid of the config cache or regenerate it:

```
% php artisan config:clear
```

**Comment by dezashibi** [comment]
Hi @tabacitu 
I also have some issue like this, I installed permission manager correctly , I added preferred menus and created one permission named "Restore" and assigned it into my role which is "Super Admin" for my user account.

I used this lines :
`if(\Auth::user()->can('Restore'))
 {
      $this->crud->addButtonFromView('line', 'restoreproj', 'restoreproj', 'beginning');
 }`

but it always shows the button even if I remove the permission from my role
this is what I get by dd(\Auth::user()->permissions);
Collection {#1372 ▼
  #items: []
}

can anybody help?

**Comment by dezashibi** [comment]
I found the issue : https://github.com/spatie/laravel-permission/issues/231#issuecomment-288251418

Here is problem file

vendor/spatie/laravel-permission/src/PermissionRegistrar.php@getPermissions()
I change form
return $this->cache->rememberForever($this->cacheKey, function () { return app(Permission::class)->with('roles')->get(); });
To
return app(Permission::class)->with('roles')->get();
It's work!
