### ISSUE TITLE
How can assign permission and role to menu when created?

### ISSUE THREAD

**Issue by Monilal** [Laravel-Backpack/PermissionManager#83]
I want to assign permission and role to menu items for multiple user.

**Comment by tabacitu** [comment]
Hi @Monilal ,

You can do that. If I were you, I'd create a permission for each menu item, assign them to the roles I want using the PermissionManager interface, then allow/disallow access using:
- [spatie/laravel-permission's blade directives](https://github.com/Laravel-Backpack/PermissionManager#using-blade-directives) in sidebar.blade.php (the actual menu);
- [using a custom middleware](https://github.com/spatie/laravel-permission#using-a-middleware) in your routes file;

Hope it helps.
Cheers!
