### ISSUE TITLE
can't delete items

### ISSUE THREAD

**Issue by tjventurini** [Laravel-Backpack/PermissionManager#84]
Hi everyone. I'm new to backpack and now I'm in some trouble making the basics work. So here is my question: why can't I delete items since I have installed the PermissionManager package?

I followed the instructions until step 6 because I don't get how I should setup my config file.

Everytime I try to delete an item, I get an 403 - Forbidden Error.

I tried to digg around the UserCrudController and the CrudController to find out where the destroy method is and what it does, but it never seems to get there. I tried to `dd('test')` in the destroy method I still just get the 403 - Forbidden Error.

In the config file there is this mentioned,

    |
    | So after the developer has entered all permissions and roles, the administrator should either:
    | - not have access to the panels
    | or
    | - creating and updating should be disabled
    */

but I can create and I have still access to everything.

Can some one help me out here? 

Thanks!

Update:

I now tried to use these in the configfile /config/backpack/permissionmanager.php but with no effect ...

    'create'                    => true,
    'update'                    => true,
    'delete'                    => true,
    'allow_create'              => true,
    'allow_update'              => true,
    'allow_delete'              => true,
    'allow_user_create'         => true,
    'allow_user_update'         => true,
    'allow_user_delete'         => true,

**Comment by tjventurini** [comment]
Got it working, not shure anymore if this is related to permissionmanager.

http://stackoverflow.com/questions/42621376/laravel-5-4-backpack-cant-delete-item-returns-403-forbidden-error

Is this the right way to do it?

**Comment by tabacitu** [comment]
Hi @tjventurini ,

Sounds more like a server issue to me - the server does not support DELETE requests. Yes, I can confirm that's a good workaround for your project. Glad you were able to sort it out.

Cheers!
