### ISSUE TITLE
How to extend Controllers?

### ISSUE THREAD

**Issue by eduardoarandah** [Laravel-Backpack/PermissionManager#88]
How to extend PermissionCrudController into PermissionController?

It would be great to allow to NOT register routes, just like dashboard does. 

I'd like to add some middleware and extra methods

**Comment by tabacitu** [comment]
By far the easiest way to create something custom would be to drag&drop the files in the ```app``` folder in your project and change namespaces. This means you won't get updates, yes, but it also means you can do whatever you want, with zero limitations :-)

I'm planning on a command line that will create extended Controllers, Requests, etc, but it will take quite some time to develop.

Hope it helps. Cheers!

**Comment by promatik** [comment]
Hi @tabacitu, I'm new to Laravel, is it possible to move only the `UserCrudController.php` to the app folder? I want to allow "admins" to edit users, but only "superadmins" can manage user roles and permissions. I think I can do all this by changing `UserCrudController.php` file only. Is this easy to accomplish?
Thanks!

**Comment by lloy0076** [comment]
@promatik - at the moment it's not terribly easy to life just ONE of the controllers out; if you really need to do this:

1. Override the routes you want in `routes/web.php`
2. Copy the default ones for the ones you don't want to meddle with
3. Extend/override the ones you do want to change.

`php artisan route:list | grep -I user` will turn up the routes you want; there's quite a few of them but they're just standard controller resource routes (and if you extend the default backpack ones you should only have to override the stuff you're interested in).

**Comment by promatik** [comment]
Thanks @lloy0076 
I was worried because to get this working, I changed the file with the routes, `vendor\Backpack\PermissionManager\src\PermissionManagerServiceProvider.php`. It would stop working with the first update.

So, for future reference, I copied the `UserCrudController.php` file to my app folder and I've extended the original one _(although there was no need for that since I changed all the methods)_.
```php
namespace App\Http\Controllers\Admin;

use Backpack\PermissionManager\app\Http\Controllers\UserCrudController as OriginalUserCrudController;
...

class UserCrudController extends OriginalUserCrudController {
...
```

And the route needed for this to work:  _(web.php)_
```php
Route::group(['prefix' => 'admin', 'middleware' => ['web', 'auth'], 'namespace' => 'Admin'], function () {
	CRUD::resource('user', 'UserCrudController');
	...
});
```

**Comment by erickleandrolima** [comment]
@promatik thanks so much man, its work for me too.

**Comment by ankitfromindia** [comment]
You should extend PermissionManagerServiceProvider
Change the route path in the extended Service Provider
Create your own User, Role and Permission Crud Controller
Set the route

`
namespace App\Providers;

class PermissionManagerServiceProvider extends \Backpack\PermissionManager\PermissionManagerServiceProvider
{
    public $routeFilePath = '/routes/backpack/custom.php';
}
`
/routes/backpack/custom.php
`Route::group([
    'prefix'     => config('backpack.base.route_prefix', 'admin'),
    'middleware' => ['web', config('backpack.base.middleware_key', 'admin')],
    'namespace'  => 'App\Http\Controllers\Admin',
], function () { // custom admin routes
    CRUD::resource('tag', 'TagCrudController');
    CRUD::resource('permission', 'PermissionCrudController');
    CRUD::resource('role', 'RoleCrudController');
    CRUD::resource('user', 'UserCrudController');
}); `
