### ISSUE TITLE
Using custom PermissionManager routes not working

### ISSUE THREAD

**Issue by baj84** [Laravel-Backpack/PermissionManager#92]
Hi, I'm trying to set up my own routes so that I can include some middleware to enforce permissions.

I have this in my web routes:

```
Route::group(['prefix' => config('backpack.base.route_prefix'), 'namespace' => '\Backpack\PermissionManager\app\Http\Controllers', 'middleware' => ['admin', 'hasRoles'], 'roles' => ['Admin']], function() {
  CRUD::resource('permission', 'PermissionCrudController');
  CRUD::resource('role', 'RoleCrudController');
  CRUD::resource('user', 'UserCrudController');
});
```

But it can't find the controllers and it throws this error:
ReflectionException in Container.php line 681:
Class App\Http\Controllers\Backpack\PermissionManager\app\Http\Controllers\UserCrudController does not exist

Do I need to tell Laravel to check in vendor files?

Thanks!

**Comment by lloy0076** [comment]
@baj84 - that's a Laravel error not a Backpack one.

For some reason, Laravel is **still** prepending `App\Http\Controllers\` to the namespace in the `Route:group`.

TBH I've always had issues with Laravel and it's <s>crap</s>automagical controller namespacing.
