### ISSUE TITLE
Let the user skip register method

### ISSUE THREAD

**Issue by eduardoarandah** [Laravel-Backpack/PermissionManager#93]
I think register method should be optional. 
( in backpack/permissionmanager/src/PermissionManagerServiceProvider.php ) 

- Maybe the user don't want to register routes, like permissions or roles
- What if the user just want to register a single method like roles->index
- What if you need extra middleware for the routes, to check permissions on the routes
- What if I want to "extend" PermissionServiceProvider and register instead MyCustomPermissionServiceProvider

I know the config file has some parameters like "allow_permission_create" "allow_permission_update" but doesn't feel right, the laravel way is using Auth / Gates / Middleware. 

Also, it would feel coherent to use PermissionManager to manage permissions in PermissionManager right? =-)

I suggest: 

- Ask the user to manually add "PermissionServiceProvider" in their config/app file like every other package
- Add a parameter "skip_setup_routes" in config/backpack/permissionmanager.php 

what do you think?

**Comment by tabacitu** [comment]
Hi @eduardoarandah ,

I agree. It's currently pretty cumbersome to overwrite/extend this. I think the best way to achieve this would be to have a ```routes/backpack``` folder. When installing PermissionManager, the ```permissionmanager.php``` routes file gets published there. If the developer wants to edit/remove any routes, he can do that there. Of course, I see this as a change across all Backpack packages.

What do you think - good solution?

Cheers!

**Comment by eduardoarandah** [comment]
@tabacitu 

Well of course!
You don't even have to document it, as it is in the official website.


### How to change/remove routes?
Via **routes/backpack** file

### How to restrict access?

Example: restrict access to permissions package 

1) Create an "admin" role 
2) Add users to that role
3) Create a "manage-permissions" permission
4) Add roles to that permission
5) Add can:manage-permissions to the route like this

`CRUD::resource('permission', 'PermissionCrudController')->middleware('can:manage-permissions');`

More info: https://laravel.com/docs/5.4/authorization#via-middleware

**Comment by lloy0076** [comment]
Issue is solved!
