### ISSUE TITLE
It has problem in mobile phones

### ISSUE THREAD

**Issue by bloggervista** [Laravel-Backpack/PermissionManager#94]
Used a mobile and it shows datatables error? Means is it problem of CORS?? If you need more details i can provide :)

**Comment by lloy0076** [comment]
1. If you can get a mobile WITH debugger, good
2. If you can open up the Laravel logs and get anything that you can see once you connect with the mobile, good
3. Any logs at all

It works on my mobile devices but I could just be lucky. OTOH I'm not sure I've tested without a CORS middleware active :)

**Comment by bloggervista** [comment]
@lloy0076  
How i got error?
Went to to users index page.
It loads all user but suppose you try to search like that it shows datat ables bootstrap type model error. 
I will check if there is logs soon :)

**Comment by lloy0076** [comment]
I'll double check this but if you do need it fixed faster, please reopen.
