### ISSUE TITLE
Call to undefined method Illuminate\Database\Query\Builder::addFakes()

### ISSUE THREAD

**Issue by rgf207** [Laravel-Backpack/PermissionManager#95]
I've been racking my brain on this for the past 2 days.  I followed the instructions to install PermissionManager.  I have the service provider added and the permissions themselves work fine.  However whenever I go to /admin/permissions or /admin/roles I get

```
Call to undefined method Illuminate\Database\Query\Builder::addFakes()
```

my user model looks like this

```php
<?php

namespace App;

use Backpack\CRUD\CrudTrait;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable {

    use CrudTrait;
    use HasRoles;
    use Notifiable;
...
```

Can't figure out what I'm doing wrong.

**Comment by lloy0076** [comment]
What's the model you have set for the `backpack.base.user_model_fqn`? (if you've published the configuration it would be in `config/backpack/base.php` very close to the end of the file).

The most immediate cause of that would be if the `CrudTrait` weren't on the model.

(ps. are there more detailed logs in `storage/logs/laravel.log`?)

**Comment by rgf207** [comment]
my user_model_fqn is
```php
  'user_model_fqn' => '\App\User',
```
And I do have CrudTrait on the model which makes this issue so weird.  It should be working I would think.

**Comment by lloy0076** [comment]
At the moment the best I could suggest is to actually intercept the builder itself (or get a trace log that is somewhat understandable) and see *what* is calling `addFakes` and work back from that; as you say it sounds like it should work.

I assume that you haven't got the development branch, are using Laravel 5.4, are on one of the more common OS (e.g. not NetBSD on your toaster :P).

**Comment by rgf207** [comment]
I'm using 2.1.16 on Homestead running laravel 5.4.  

How would I intercept the builder?

**Comment by lloy0076** [comment]
It might be a tad tedious to intercept the builder (but it's one way to trace what's happening).

Have you overridden the default crud controller(s) by any chance?

**Comment by rgf207** [comment]
yes I did override them. I have it in App\Http\Controllers\Admin\PermissionCrudController

```php
<?php

namespace App\Http\Controllers\Admin;

use Backpack\PermissionManager\app\Http\Controllers\PermissionCrudController as BackpackPermissionCrudController;

class PermissionCrudController extends BackpackPermissionCrudController {

    public function __construct()
    {
        $this->middleware('Administrator');

        parent::__construct();
    } // __construct
}
```

**Comment by lloy0076** [comment]
What's it do if you take the middleware clause out?

**Comment by lloy0076** [comment]
I don't know if I can help solve without examining the source code (which may or may not be possible), or at the very least looking at the `storage/logs/laravel.log` [which probably won't be much more helpful than the reported error but occasionally it'll show something new].

The only case I've seen the `addFakes` issue is when some `laravel-Backpack/CRUD` controller gets a model that doesn't implement the `CrudTrait` and/or has somehow made a mess of the `addFakes()` method such that it compiles cleanly but displays weird runtime errors.

**Comment by Frondor** [comment]
This is happening because the model in the resource, is the original `Role` from Spatie, not the one in this package using `CrudTrait`. 

I had to manually update it in `config/laravel-permission.php`

**Comment by tabacitu** [comment]
I think this usually happens by not publishing the files with ```php artisan vendor:publish --provider="Backpack\PermissionManager\PermissionManagerServiceProvider"```, but with ```php artisan vendor:publish```. 

We overwrite some ```config/laravel-permission.php``` options, like the Role and Permission classes, and you don't get that if you don't follow the installation procedure thoroughly...

**Comment by lloy0076** [comment]
@Tabacitu - this overwriting of that file seems to happen more often than not; I wonder if there's something we could do that would detect this (I'm thinking some check that checks to see if the model really does implement the trait [somehow] and then throws a nicer error than the default PHP one; the default PHP one is true but not necessarily helpful).

**Comment by Frondor** [comment]
You can use contextual binding instead of overwriting configs (which doesn't feels good) if you are willing to use DI and extending default Role model, like
```
$this->app->when(SomeController::class)
          ->needs(Role::class)
          ->give(function () {
              return new ExtendedRole();
          });
```

**Comment by lloy0076** [comment]
This is an enhancement awaiting a PR.

@tabacitu What do you think of the above proposed solution?

**Comment by cvassios-ekko** [comment]
I think I'm getting the same issue, but its odd because everything was working on my local dev environment, but got this issue when I moved it live. I followed everything up to the part about `config/laravel-permission.php` becuase I don't have that file.

**Comment by tabacitu** [comment]
@cvassios-ekko running ```php artisan vendor:publish --provider="Backpack\PermissionManager\PermissionManagerServiceProvider"``` in production should fix it for you.

@lloy0076 and @Frondor - I'm totally open to that, but I'm not sure contextual binding is a solution for everything we've changed in ```config/laravel-permission.php```:
1. the models (Permission and Role) - we might be able to do that; 
2. User Permissions Table, User Roles Table, Role Permissions Table (changed syntax from the one prefered by spatie [```user_has_permissions```] to the laravel-recommended and laracasts-recommended one [```user_permissions```]);

Since contextual binding might fix (1), but not (2), we'd still have to overwrite the config file. So if we do, I'd rather not use contextual binding at all, because it would only add another layer of complexity to how PermissionManager works. People would check what model is used in the config file, see that it's ```Spatie\Permission\Models\Permission::class```, but actually the CRUD will be using ```Backpack\PermissionManager\app\Models\Permission::class```. I think that would just add confusion...

That being said, I would LOVE to remove this configuration-overwriting thing. I'll close this issue for now, but if anybody figures out another way to NOT overwrite the config file, please reopen.

Cheers!

**Comment by cvassios-ekko** [comment]
@tabacitu Thanks, I ended up manually uploading the vendor files to production and that solved it. Good to know there is a command that can do that for me in the future.
